(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.b11 = function() {
	this.initialize(img.b11);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


(lib.b12 = function() {
	this.initialize(img.b12);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


(lib.b13 = function() {
	this.initialize(img.b13);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


(lib.b14 = function() {
	this.initialize(img.b14);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


(lib.Bitmap1 = function() {
	this.initialize(img.Bitmap1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,104,72);


(lib.Bitmap2 = function() {
	this.initialize(img.Bitmap2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,134,102);


(lib.Bitmap3 = function() {
	this.initialize(img.Bitmap3);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,158,126);


(lib.lg336 = function() {
	this.initialize(img.lg336);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,78,55);


(lib.lg_37 = function() {
	this.initialize(img.lg_37);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,102,72);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Symbol98 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 4
	this.instance = new lib.Bitmap3();
	this.instance.parent = this;
	this.instance.setTransform(-32,-32);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer 3
	this.instance_1 = new lib.Bitmap2();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-20,-20);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Layer 2
	this.instance_2 = new lib.Bitmap1();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-5,-5);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AnCElQgFgIARg4QAUhCAGgYQAKgnAHgKQAJgOAggTQAagOBxgwQCEg5AdgOQAxgXAjgbIAtgoQAVgTBvg2QBzg5ATAEQAXAFAkAkQAmAmAHAfQAJAngDAmQgEAugYAlQgaAphfAxQhjAziGAmIk2BZQivAvggAAIgCAAg");
	this.shape.setTransform(45.1659,29.339);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol98, new cjs.Rectangle(-32,-32,158,126), null);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAPAoIgigiIAAAiIgLAAIAAhPIAKAAIAAAjIAkgjIAPAAIgrAnIArAog");
	this.shape.setTransform(104.675,24.825);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AATAoIAAg+IgkA+IgLAAIAAhPIAKAAIAAA+IAkg+IALAAIAABPg");
	this.shape_1.setTransform(95.675,24.825);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgdAoIAAhPIAcAAIAEAAIANABQAHABADAEQADAFAAAJQAAAPgIAEQAFABACAEQACAEAAAIQAAARgLAEIgHACIgMAAgAgSAfIARAAIAFAAIAHgBIAFgCQADgDAAgIQAAgGgCgDQgCgDgFgBIgLAAIgRAAgAgSgFIARAAIAFAAIAHAAIAEgCQAEgDAAgHQAAgGgDgDQgCgDgFAAIgLAAIgQAAg");
	this.shape_2.setTransform(86.975,24.825);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgWAkQgGgFgCgKQgBgGAAgPQAAgOABgHQACgJAGgFQAIgFAOAAQAPAAAHAFQAHAEABAKQACAGAAAPQAAAPgCAGQgCALgGAEQgHAFgPAAQgOAAgIgFgAgMgdQgDACgCADQgCADgBAFIgBAQIABAQQABAGACADQACADAEACQAFABAGAAQAIAAAEgBQAEgCACgDIACgJIABgQIgBgQQAAgFgCgDQgCgDgFgCQgDgBgIgBQgHAAgFACg");
	this.shape_3.setTransform(78.05,24.85);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAVAoIgVghIgTAhIgMAAIAagoIgagnIAMAAIATAgIAUggIAMAAIgaAnIAbAog");
	this.shape_4.setTransform(69.55,24.825);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AAVAoIAAgiIgIAAIgGAAIgDACIgGAJIgQAXIgMAAIAXgjQgUgBAAgUQAAgLAFgFQADgFAIgBIAPgBIAbAAIAABPgAgHgdQgFABgCACQgCAEAAAGQAAAHACACQABADAEABIAKAAIAUAAIAAgaIgSAAIgKAAg");
	this.shape_5.setTransform(60.925,24.825);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AggAfQAFAAACgCQAEgCACgJIANg6IAnAAIAABQIgLAAIAAhGIgUAAIgLAzIgDAJIgEAGQgFAFgLAAg");
	this.shape_6.setTransform(51.925,24.875);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgqAoIAAhPIALAAIAABGIAbAAIAAhGIAJAAIAABGIAbAAIAAhGIALAAIAABPg");
	this.shape_7.setTransform(42.325,24.825);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAZAoIgIgWIghAAIgIAWIgLAAIAfhPIAJAAIAfBPgAgNAJIAaAAIgNgjg");
	this.shape_8.setTransform(32.275,24.825);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgWAkQgIgFAAgMIALAAQAAAHAFADQAEACAKAAQAMAAAEgDQAEgDAAgHIgBgJQgCgEgEgBIgNgBIgIAAIAAgIIAIAAQALAAAFgCQAEgEAAgHQAAgFgCgCQgBgDgFgCIgMgBQgLAAgEADQgEAEAAAHIgLAAQAAgOAKgGQAHgDANAAQARAAAHAGQAGAEAAALQAAAHgCAFQgDAEgGACQAHABACAEQADAEAAAKQAAANgJAGQgIAEgOAAQgPAAgHgFg");
	this.shape_9.setTransform(23.525,24.85);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgVAkQgHgFgCgKQgBgGAAgPQAAgOABgHQACgJAHgFQAHgFAOAAQAPAAAIAFQAFAEADAKQABAGAAAPQAAAPgBAGQgCALgHAEQgHAFgPAAQgOAAgHgFgAgMgdQgDACgCADQgCADgBAFIgBAQIABAQQABAGACADQACADAEACQAEABAHAAQAIAAAEgBQADgCACgDIAEgJIAAgQIAAgQQgCgFgCgDQgCgDgDgCQgFgBgHgBQgHAAgFACg");
	this.shape_10.setTransform(14.75,24.85);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AATAoIAAhGIgkAAIAABGIgLAAIAAhPIA5AAIAABPg");
	this.shape_11.setTransform(5.8,24.825);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AATA0IAAg/IgkA/IgLAAIAAhQIAKAAIAAA/IAkg/IALAAIAABQgAgNgnQgDgEAAgIIAHAAQAAAFACABQACACAFAAQAGAAACgCQACgBAAgFIAHAAQAAAJgEADQgEAEgJgBQgJAAgEgDg");
	this.shape_12.setTransform(103.525,9.25);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AATAoIAAg+IgkA+IgLAAIAAhPIAKAAIAAA+IAkg+IALAAIAABPg");
	this.shape_13.setTransform(94.725,10.425);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AATAoIAAgkIgkAAIAAAkIgLAAIAAhPIALAAIAAAiIAkAAIAAgiIAKAAIAABPg");
	this.shape_14.setTransform(85.9,10.425);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgdAoIAAhPIALAAIAAAiIARAAIAPABQAIACAEADQAEAFAAALQAAALgEAFQgEAFgIABIgPABgAgSAfIARAAIAEAAQAHAAAEgCQAFgDAAgJQAAgJgFgDQgEgBgHAAIgEAAIgRAAg");
	this.shape_15.setTransform(77.575,10.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AggAfQAFAAACgCQAEgCACgJIANg6IAnAAIAABQIgLAAIAAhGIgUAAIgLAzIgDAJIgEAGQgFAFgLAAg");
	this.shape_16.setTransform(68.325,10.475);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AAZAoIgIgWIghAAIgIAWIgLAAIAfhPIAJAAIAfBPgAgNAJIAaAAIgNgjg");
	this.shape_17.setTransform(60.275,10.425);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgUAkQgHgFgCgKQgBgGAAgPQAAgOABgHQACgJAHgFQAHgFAPAAQAQAAAGAGQAHAFAAAMIgKAAQgBgGgBgCQgCgDgEgBQgEgBgIgBQgJAAgFADQgEAEgBAHIgBARIABASQABAIAEACQAFADAJAAQAMAAAEgDQADgDABgGIAKAAQAAANgIAFQgIAEgNAAQgPAAgHgFg");
	this.shape_18.setTransform(51.75,10.45);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgdAoIAAhPIAcAAIAPABQAIABAEAFQAEAFgBALQABALgEAFQgEAEgIABIgPABIgQAAIAAAigAgRgCIAPAAIAEAAQAJAAACgCQAGgDAAgJQAAgJgGgDQgCgBgJAAIgEAAIgPAAg");
	this.shape_19.setTransform(43.4,10.425);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgaAoIAAhPIA1AAIAAAKIgqAAIAAAYIAoAAIAAAJIgoAAIAAAbIAqAAIAAAJg");
	this.shape_20.setTransform(35.05,10.425);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgdAoIAAhPIAcAAIAEAAIANABQAHABADAEQADAFAAAJQAAAPgIAEQAFABACAEQACAEAAAIQAAARgLAEIgHACIgMAAgAgSAfIARAAIAFAAIAHgBIAFgCQADgDAAgIQAAgGgCgDQgCgDgFgBIgLAAIgRAAgAgSgFIARAAIAFAAIAHAAIAEgCQAEgDAAgHQAAgGgDgDQgCgDgFAAIgLAAIgQAAg");
	this.shape_21.setTransform(26.625,10.425);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AgEAoIAAhPIAJAAIAABPg");
	this.shape_22.setTransform(20.15,10.425);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AATAoIAAgkIgkAAIAAAkIgMAAIAAhPIAMAAIAAAiIAkAAIAAgiIAKAAIAABPg");
	this.shape_23.setTransform(13.7,10.425);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgTAoIAOgaIgcg1IAMAAIAVAqIAWgqIAMAAIgpBPg");
	this.shape_24.setTransform(5.375,10.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol22, new cjs.Rectangle(0,0,110.9,34.4), null);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.b13();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol21, new cjs.Rectangle(0,0,336,280), null);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0C121C").s().p("AG3AxQgHgGAAgNQAAgPALgGQAHgDAOAAIATAAIgBgHIgCgDQgDgDgKAAQgIAAgDABQgFACAAAEIgRAAQAAgNAMgFQAIgEAOAAQAgAAAAAaIAAAxIgQAAIAAgGQgIAHgPAAQgPAAgHgFgAHEAWQgDACAAAGQAAAGAEACQADACAIAAQANAAAEgGQACgDAAgLIgUAAQgIAAgDACgAFVAqIgCgIIgBgPIAAgoIASAAIAAAtIAAAIIACAEQADADAIAAQAMAAAEgHQACgEAAgKIAAgnIARAAIAABKIgPAAIAAgGQgIAHgNAAQgWAAgFgMgAEkAzQgDgDAAgEQAAgLALAAQALAAAAALQAAAFgEADQgCACgFAAQgGAAgCgDgAB1AqQgGgIAAgRQAAgNADgHQACgJAHgFQAJgFAOAAQAPAAAIAGQAHAFADALQABAGAAAQIgzAAQAAALAEAEQAEADAKAAQAQAAAAgJIAQAAQAAAOgMAGQgIADgNAAQgWAAgHgMgACFgEQgEADAAAJIAiAAIgBgIQAAAAAAgBQAAAAAAgBQgBAAAAgBQAAAAgBgBQgEgEgKAAQgKAAgDAEgAg6A0QgHgCgEgEQgFgEgBgHQgCgHAAgMQAAgNACgFQABgIAFgEQAFgFAHgCQAHgBAJAAQATAAAIAIQAFAEABAHQACAGAAANQAAAMgBAHQgCAHgFAEQgIAIgTAAQgLAAgGgCgAg2gEQgDACgBADQgCAEAAALIABAMQABAEACACQADAFAMAAQAIAAAEgCQADgCACgFIABgOIgBgNQgBgDgCgCQgDgFgLAAQgJAAgEADgAj+AoQgCgEgBgFIgBgPQAAgUAGgIQAHgKARAAQAQAAAGAHIAAgmIASAAIAABqIgQAAIAAgGQgEAEgGACQgGABgHAAQgVAAgGgOgAjqgEQgEACgBAEQgBAEAAAKQAAAOADAFQADAEAJAAQAIAAAEgCQAEgCACgFQACgFAAgJQAAgKgCgFQgCgDgEgCQgEgCgIAAQgGAAgDACgAm5AxQgHgGAAgNQAAgPAMgGQAGgDAOAAIAUAAIgBgHIgCgDQgDgDgKAAQgIAAgEABQgFACAAAEIgRAAQAAgNAMgFQAIgEAPAAQAfAAAAAaIAAAxIgPAAIAAgGQgJAHgPAAQgPAAgHgFgAmsAWQgCACAAAGQAAAGADACQADACAIAAQAOAAADgGQADgDAAgLIgUAAQgJAAgDACgAnWA2QgOAAgGgEQgJgGAAgOIAAhTIASAAIAABOIAAAIIACAEQACADAHAAIAFAAIAAAOgADQA1IAAhKIAQAAIAAAHQAHgIANAAQANAAAGAGQAGAGAAALIgRAAQAAgFgDgCIgIgBQgFAAgDACQgEADgBADQgCAFAAAKIAAAlgAArA1IgdhKIATAAIATA2IAUg2IASAAIgdBKgAieA1IAAhKIAQAAIAAAHQAHgIANAAQANAAAGAGQAGAGAAALIgRAAQAAgFgDgCIgIgBQgFAAgDACQgEADgBADQgCAFAAAKIAAAlgAkuA1IAAgnIAAgMQgBgEgCgCQgDgDgIAAQgLAAgEAHQgCAEAAAJIAAAoIgSAAIAAhKIAQAAIAAAGQAIgHANAAQAVAAAGANIACAIIAAANIAAApg");
	this.shape.setTransform(53.125,13.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol18, new cjs.Rectangle(0,0,107.5,25.2), null);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AOxC4IAAgUIhNAAIAAhuIARAAIAABfIAwAAIAAhfIARAAIAABfIALAAIAAAjgAQ7CgQgJgHgEgLQgCgJAAgRIgWAAIAAAwIgRAAIAAhuIARAAIAAAuIAWAAQAAgQACgJQAEgKAJgGQAKgGAUAAQAVAAAJAHQAKAHADANQABAIAAAVQAAAVgCAJQgDAOgJAGQgKAHgUAAQgUAAgKgGgARGBHQgFAEgCAHQgCAIAAANIAAAGQAAATABAGQACAKAGADQAGADANAAQALAAAHgFQAGgEACgKQABgHAAgPIAAgDQAAgPgBgIQgDgHgFgEQgGgEgMABQgNAAgGACgAKKCfQgKgIAAgRIAQAAQAAAGADAEQACADAFACQAGABAKAAQARAAAGgEQAFgDAAgKQAAgIgCgDQgCgFgGgBQgEgBgNAAIgNAAIAAgPIANAAQAPAAAGgDQAEgEAAgJQAAgGgBgEQgCgDgGgBQgFgBgMAAQgPgBgGAEQgFAEAAAIIgRAAQAAgTAOgHQAKgFATAAQAYAAAKAIQAJAGAAAPQAAAJgDAHQgEAGgIADQAJADAEAGQADAFAAANQABASgNAIQgLAGgVAAQgWAAgKgHgAIcCfQgJgHgDgOQgBgIAAgVQAAgVABgIQADgNAJgHQAKgHAVAAQAWAAAJAHQAJAHAEANQABAIAAAVQAAAVgCAJQgDAOgJAGQgKAHgUAAQgWAAgKgHgAIpBIQgGAEgCAIQgCAIABARQgBARACAHQACAKAGADQAGAEANAAQAMAAAGgEQAGgDACgKQABgHAAgRQAAgRgBgIQgCgIgGgEQgGgEgNABQgNgBgFAEgAE5CfQgIgHgDgOQgCgIAAgVQAAgVACgIQADgNAIgHQAKgHAWAAQAVAAAKAHQAJAHADANQACAIAAAVQAAAVgDAJQgCAOgKAGQgKAHgUAAQgVAAgLgHgAFGBIQgFAEgCAIQgCAIAAARQAAARACAHQABAKAHADQAFAEANAAQAMAAAHgEQAFgDACgKQABgHABgRQgBgRgBgIQgCgIgFgEQgHgEgMABQgNgBgGAEgAmRCWQAHAAAFgFQAEgFABgGIAShQIA5AAIAABuIgRAAIAAheIgaAAIgQBFQgCAMgDAEQgEAGgGACQgGADgMAAgArKCfQgJgHgCgOQgCgIgBgVQABgVACgIQACgNAJgHQAKgHAVAAQAVAAALAHQAJAHACANQACAIAAAVQAAAVgCAJQgDAOgJAGQgKAHgVAAQgUAAgLgHgAq+BIQgFAEgCAIQgCAIAAARQAAARACAHQACAKAGADQAFAEANAAQANAAAGgEQAFgDACgKQACgHAAgRQAAgRgCgIQgCgIgFgEQgGgEgNABQgMgBgHAEgAs4CfQgJgHgDgOQgCgJAAgUQAAgVACgIQADgOAJgFQAKgIAWAAQAWAAAKAIQAIAHABAQIgRAAQAAgGgCgDQgDgEgEgBQgGgBgLAAQgLgBgHAEQgFAEgCAIQgBAIgBARQABARABAIQACAJAFADQAGAEAMAAQAQAAAFgEQAFgDAAgJIARAAQgBATgMAHQgJAGgTAAQgWAAgKgHgAPVCkIAAhuIARAAIAABugAM1CkIAAhTIgxBTIgRAAIAAhuIAQAAIAABTIAwhTIASAAIAABugAHiCkIAAhfIgwAAIAABfIgRAAIAAhuIBSAAIAABugADECkIAAhuIAmAAQAQAAAHABQALACAFAHQAGAHAAAPQAAAPgGAHQgFAIgKABQgIACgQAAIgVAAIAAAtgADVBoIAbAAQALgBAEgCQAHgDAAgLQAAgMgHgEQgEgCgLAAIgbAAgACVCkIAAhfIgwAAIAABfIgRAAIAAhuIBTAAIAABugAg1CkIATgkIgnhKIATAAIAeA4IAcg4IATAAIg5BugAhrCkIAAgwIgxAAIAAAwIgRAAIAAhuIARAAIAAAuIAxAAIAAguIARAAIAABugAkXCkIAAhuIARAAIAAAuIAWAAIAWABQALACAGAHQAFAHABAPQgBAPgFAHQgGAHgLACQgGABgQAAgAkGCVIAcAAQAKAAAEgCQAHgDAAgMQAAgLgHgEQgEgBgLAAIgbAAgAmqCkIgLgdIgtAAIgKAdIgSAAIAqhuIASAAIArBugAndB4IAiAAIgRgvgAohCkIAAgwIgxAAIAAAwIgRAAIAAhuIARAAIAAAuIAxAAIAAguIARAAIAABugAutCkIAAhuIAmAAQAPAAAHABQALACAFAHQAGAHAAAPQAAAPgGAHQgFAIgLABQgHACgPAAIgVAAIAAAtgAucBoIAaAAQALgBAEgCQAHgDAAgLQAAgMgHgEQgFgCgJAAIgbAAgAwUCkIAAhuIBLAAIAAAPIg6AAIAAAfIA4AAIAAAQIg4AAIAAAhIA6AAIAAAPgAxDCkIAAhfIgwAAIAABfIgRAAIAAhuIBSAAIAABugAnTgtQgIgHgDgNQgCgJAAgVQAAgVACgIQADgNAIgHQAKgHAWAAQAVAAAKAHQAJAHADANQABAIABAVQAAAVgCAJQgEAOgJAGQgJAHgVAAQgVAAgLgHgAnGiEQgFADgDAKQgBAHAAARQAAARABAHQACAJAHAFQAFADANAAQANAAAFgEQAGgEACgJQABgHABgRQgBgRgBgHQgCgKgGgDQgFgDgNAAQgNAAgGADgAGVgnIAAhvIBLAAIAAAPIg6AAIAAAfIA4AAIAAAPIg4AAIAAAiIA6AAIAAAQgAFOgnIAAhgIgiAAIAAgPIBVAAIAAAPIgiAAIAABggAEJgnIAAhUIgxBUIgSAAIAAhvIAQAAIAABTIAxhTIASAAIAABvgACggnIgKgeIgtAAIgKAeIgSAAIArhvIARAAIAqBvgABvhUIAhAAIgQgvgAAqgnIAAhXIgeBXIgPAAIgghXIAABXIgPAAIAAhvIAWAAIAgBaIAghaIAXAAIAABvgAhggnIAAhUIgxBUIgSAAIAAhvIAQAAIAABTIAxhTIASAAIAABvgAkNgnIAAhvIAnAAQAPAAAHABQALADAFAGQAGAHAAAPQAAAPgGAHQgFAIgLABQgHACgPAAIgWAAIAAAugAj8hkIAbAAQALAAAEgCQAHgEAAgLQAAgNgHgDQgEgCgLAAIgbAAgAlTgnIAAhgIgiAAIAAgPIBVAAIAAAPIgjAAIAABggADcinQgFgEAAgMIAMAAQAAAHACACQADACAHAAQAIAAACgCQADgCAAgHIAMAAQgBANgFAFQgGADgNAAQgOAAgFgFg");
	this.shape.setTransform(129.5,-9.85);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol17, new cjs.Rectangle(8.7,-35,241.9,50.3), null);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ApZA9IAAgPIg0AAIAAAPIgOAAIAAgcQAHAAACgDQADgDABgGIAOg4IArAAIAABEIAJAAIAAAcgAp/AWQgCAJgEACIAiAAIAAg3IgSAAgAE6AiQAGAAADgDQADgCACgHIANg5IArAAIAABRIgOAAIAAhDIgSAAIgLAwIgEALQgDAFgFACQgFACgKAAgAgEAqQgHgFgCgKQgBgHAAgPQAAgOABgGQACgKAHgFQAHgGAQAAQAQAAAIAGQAHAGAAAMIgOAAQAAgEgCgCQgBgDgEgBIgLgBQgIAAgEADQgEACgBAGQgBAFAAAMIAAASQACAGAEADQAEACAIAAQALAAAEgDQADgCAAgGIAOAAQAAAOgJAGQgIAEgOAAQgQAAgHgFgAoHAqQgIgGAAgNIAPAAQAAAFABACQACACADABIAMABQALAAAEgDQAEgCAAgHQAAgFgBgCQgCgDgDgBIgNgBIgKAAIAAgLIAKAAQALAAAEgDQADgCAAgGIgBgGQgBgDgEgBIgNgBQgLAAgDADQgEACAAAGIgOAAQAAgOAKgGQAIgEAOAAQATAAAHAGQAHAFAAALQAAAHgDAEQgCAEgHADQAJACACAGQACAEAAAHQAAAOgKAGQgIAEgQAAQgRAAgHgFgAJkAuIAAhRIA4AAIAAANIgqAAIAAAVIApAAIAAAMIgpAAIAAAWIAqAAIAAANgAHvAuIAAhRIAOAAIAABEIAYAAIAAhEIAOAAIAABEIAYAAIAAhEIAOAAIAABRgAGbAuIAAhRIAOAAIAAAiIAOAAQAMAAAFABQAJABAEAEQAEAGAAALQAAALgEAGQgEAFgJABIgRABgAGpAhIATAAIAKgBQAFgCAAgIQAAgEgCgCQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAgBQgDgBgIAAIgSAAgAEaAuIAAhRIAPAAIAABRgADHAuIAAhRIA3AAIAAANIgpAAIAAAVIATAAQAJAAAGABQAHABADAFQAEAGAAAKQAAALgEAGQgEAFgJABIgRABgADVAhIATAAIAKgBQAFgCAAgIQAAgEgCgCQAAgBAAAAQgBgBAAAAQgBgBAAAAQgBAAAAgBQgDgBgIAAIgSAAgAB6AuIAAghIgEAAIgGABQgBAAAAAAQgBAAAAAAQgBAAAAABQAAAAgBAAIgHAKIgOAVIgRAAIAXgiQgLgBgFgJQgDgEAAgJQAAgLAFgFQAEgFAIgCIARgBIAdAAIAABRgABcgUQgEACAAAIQAAAFACADQAAAAABABQAAAAABABQAAAAABAAQAAAAABAAIAKAAIASAAIAAgWIgQAAIgKAAIgEACgAhdAuIAAhRIA4AAIAAANIgqAAIAAAVIApAAIAAAMIgpAAIAAAWIAqAAIAAANgAiZAuIAAhEIgZAAIAAgNIBBAAIAAANIgZAAIAABEgAjTAuIAAg6IgiA6IgPAAIAAhRIAOAAIAAA6IAig6IAPAAIAABRgAklAuIgIgVIggAAIgIAVIgPAAIAghRIAPAAIAfBRgAlJANIAXAAIgLgggAmEAuIAAgjIgiAAIAAAjIgOAAIAAhRIAOAAIAAAiIAiAAIAAgiIAOAAIAABRgAo2AuIAAhRIAPAAIAABRgAjzgvQgEgEAAgJIAJAAQAAAFACACQACABAFAAQAGAAABgBQADgCAAgFIAIAAQAAAKgEAEQgEADgKAAQgLAAgDgEg");
	this.shape.setTransform(100.875,21.875);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol16, new cjs.Rectangle(30.9,10.5,141.5,22.799999999999997), null);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgFArIAAhVIALAAIAABVg");
	this.shape.setTransform(167.725,11.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AgFArIAAhLIgbAAIAAgKIBBAAIAAAKIgbAAIAABLg");
	this.shape_1.setTransform(161.525,11.325);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgWAnQgHgGgCgKIgBgXQAAgQABgGQACgLAHgFQAIgFAQAAQARAAAHAGQAHAFAAANIgLAAQAAgFgCgDQgCgDgEgCIgNgBQgKAAgFADQgEAEgCAHIgBATIABAUQACAHAEADQAFAEAKAAQANAAAEgEQAEgCAAgIIALAAQAAAOgJAGQgHAEgPAAQgQAAgIgFg");
	this.shape_2.setTransform(152.875,11.325);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AgXAnQgHgFgCgLQgCgHABgQQgBgQACgGQACgLAHgFQAIgFAPAAQARAAAHAFQAIAFABALIABAWQAAAQgBAHQgCALgHAFQgIAFgQAAQgPAAgIgFgAgMgfQgEACgCADQgCADgBAGIgBARIABASQABAGACADQACADAEACQAFACAHAAQAIAAAFgCQAEgCADgDQACgDAAgGIABgSIgBgRQAAgGgCgDQgDgEgFgBQgEgCgIAAQgIAAgEACg");
	this.shape_3.setTransform(143.2,11.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AAUArIAAgnIgnAAIAAAnIgMAAIAAhVIAMAAIAAAlIAnAAIAAglIAMAAIAABVg");
	this.shape_4.setTransform(133.575,11.325);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AgfArIAAhVIAeAAIAEAAIAOABQAHABADAEQAEAGAAAJQAAARgIADQAFACACAEQACAFAAAIQAAASgMAFIgIACIgNAAgAgUAhIASAAIAGAAIAIgBIAFgCQAEgDAAgIQAAgIgDgDQgCgDgGgBIgMAAIgSAAgAgUgFIATAAIAFAAIAIgBQABAAAAAAQABAAAAgBQABAAAAAAQABAAAAgBQAEgDAAgIQAAgHgDgDQgCgCgFgBIgMAAIgSAAg");
	this.shape_5.setTransform(124.175,11.325);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AAXArIAAglIgJAAIgGABIgEABIgGAKIgRAZIgOAAIAZgmQgUgBAAgVQgBgMAFgGQAEgFAIgBIARgBIAdAAIAABVgAgIggQgFABgCADQgCAEAAAHQgBAHACADQACACAFABIAKABIAWAAIAAgdIgUAAIgLAAg");
	this.shape_6.setTransform(114.35,11.325);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AAbArIgJgYIgjAAIgJAYIgMAAIAhhVIALAAIAhBVgAgOAJIAcAAIgOgmg");
	this.shape_7.setTransform(105.275,11.325);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#000000").s().p("AAUArIAAgnIgnAAIAAAnIgMAAIAAhVIAMAAIAAAlIAnAAIAAglIAMAAIAABVg");
	this.shape_8.setTransform(95.925,11.325);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgUArIAPgcIgfg5IAOAAIAWAtIAYgtIANAAIgsBVg");
	this.shape_9.setTransform(82.8,11.325);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("AgbArIAAhVIA3AAIAAAKIgsAAIAAAbIArAAIAAAJIgrAAIAAAdIAsAAIAAAKg");
	this.shape_10.setTransform(70.15,11.325);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#000000").s().p("AgFArIAAhLIgbAAIAAgKIBBAAIAAAKIgbAAIAABLg");
	this.shape_11.setTransform(61.675,11.325);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#000000").s().p("AAVA4IAAhDIgoBDIgLAAIAAhVIAKAAIAABDIAnhDIANAAIAABVgAgOgrQgDgDgBgJIAIAAQAAAFACACQACACAGAAQAGAAACgCQACgCAAgFIAIAAQABAKgFADQgEADgKAAQgKAAgEgEg");
	this.shape_12.setTransform(52.9,10.025);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AAbArIgJgYIgjAAIgJAYIgMAAIAhhVIALAAIAhBVgAgOAJIAcAAIgOgmg");
	this.shape_13.setTransform(43.575,11.325);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgfArIAAhVIAeAAIAQABQAIABAEAFQAFAGAAALQAAAMgFAGQgEAEgIABIgQABIgSAAIAAAlgAgTgDIARAAIAFAAQAIAAADgCQAGgDAAgKQAAgJgGgDQgDgCgIAAIgFAAIgRAAg");
	this.shape_14.setTransform(34.775,11.325);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AAVArIAAhDIgnBDIgMAAIAAhVIAKAAIAABDIAnhDIANAAIAABVg");
	this.shape_15.setTransform(25.25,11.325);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgfArIAAhVIA3AAIAAAKIgrAAIAAAbIASAAIARABQAIABAEAEQAEAGAAALQAAAMgEAFQgEAGgIABIgRABgAgTAhIASAAIADAAQAJAAADgCQAHgDgBgKQABgJgHgDQgDgCgJAAIgDAAIgSAAg");
	this.shape_16.setTransform(16.05,11.325);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgXAnQgHgFgCgLQgBgHgBgQQABgQABgGQACgLAHgFQAIgFAPAAQAQAAAJAFQAGAFADALIABAWQgBAQgBAHQgCALgHAFQgIAFgQAAQgPAAgIgFgAgMgfQgEACgCADQgDADAAAGIgBARIABASQAAAGADADQACADAFACQAEACAHAAQAIAAAFgCQAEgCACgDQACgDACgGIAAgSIAAgRQgCgGgCgDQgCgEgFgBQgEgCgIAAQgIAAgEACg");
	this.shape_17.setTransform(6.35,11.325);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol12, new cjs.Rectangle(0,0,172.6,21.6), null);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AIGAzIAAgPIg5AAIAAAPIgLAAIAAgZQAGAAADgEQADgDABgFIAPg/IArAAIAABLIAIAAIAAAZgAHaAOQgCAJgDADIAoAAIAAhBIgVAAgAI0AgQgHgFgCgLQgBgHgBgPQABgRABgGQACgLAHgFQAIgFAQAAQAQAAAJAFQAGAFADALIABAXQgBAPgBAHQgCALgHAFQgIAFgQAAQgQAAgIgFgAI/gmQgEACgCADQgDADAAAGIgBASIABARQAAAGADADQACADAFACQAEACAIAAQAJAAAEgCQAEgCACgDQACgDACgGIAAgRIAAgSQgCgGgCgDQgCgEgFgBQgEgCgIAAQgJAAgEACgAFyAgQgJgGABgNIALAAQAAAJAGACQAEADAMAAQAMAAAGgEQAEgDAAgIQAAgHgBgDQgCgCgFgBIgOgBIgLAAIAAgKIALAAQAMAAAEgDQAFgEAAgHQAAgGgBgCQgCgEgFgBIgNgBQgOAAgEADQgEADAAAIIgLAAQAAgPAKgGQAHgDAQAAQASAAAHAFQAIAGgBALQABAIgDAFQgDAFgGACQAHACACAFQADADAAAKQAAAOgKAHQgHAEgQAAQgSAAgHgFgAlTAgQgHgGgCgKIgBgWQgBgRACgGQACgLAHgFQAIgFARAAQAQAAAIAGQAHAFAAANIgLAAQgBgFgBgDQgCgDgFgCIgMgBQgLAAgFADQgEAEgCAHIgBAUIABATQACAHAEADQAFAEALAAQANAAAEgEQADgCABgIIALAAQAAAOgKAGQgGAEgPAAQgRAAgIgFgAQGAkIAAhVIAMAAIAABVgAPhAkIgiglIAAAlIgLAAIAAglIgjAlIgPAAIAogrIgogqIAPAAIAjAkIAAgkIALAAIAAAkIAjgkIAPAAIgpAqIApArgANnAkIghglIAAAlIgNAAIAAglIghAlIgQAAIAogrIgogqIAPAAIAiAkIAAgkIAMAAIAAAkIAjgkIAOAAIgoAqIAoArgALnAkIAAhVIAMAAIAABVgAKNAkIAAhVIAeAAIARABQAIABAEAFQAFAGgBALQABAMgFAGQgEAFgIABIgRABIgSAAIAAAkgAKZgKIAWAAQAJAAADgCQAGgDAAgKQAAgJgGgDQgDgCgJAAIgWAAgAEWAkIAAhVIA5AAIAAAKIguAAIAAAbIAsAAIAAAKIgsAAIAAAcIAuAAIAAAKgAC5AkIAAhVIA4AAIAAAKIgsAAIAAAbIASAAIASABQAIABAEAFQAEAFAAALQAAAMgEAFQgEAGgIABIgSABgADFAaIAWAAQAJAAADgCQAHgDgBgKQABgJgHgCQgDgCgJAAIgWAAgABtAkIgJgYIgkAAIgJAYIgMAAIAhhVIAMAAIAhBVgABDACIAdAAIgOgmgAAJAkIAAgmIgoAAIAAAmIgLAAIAAhVIALAAIAAAlIAoAAIAAglIALAAIAABVgAiuAkIAAhVIAMAAIAAAlIATAAIARABQAIABAEAFQAFAFgBALQABAMgFAFQgEAGgIABIgRABgAiiAaIAXAAQAIAAAEgCQAGgDAAgKQAAgJgGgCQgEgCgIAAIgXAAgAjsAkIAAhLIgbAAIAAgKIBCAAIAAAKIgbAAIAABLgAmIAkIAAhVIAMAAIAABVgAmzAkIAAgmIgoAAIAAAmIgMAAIAAhVIAMAAIAAAlIAoAAIAAglIAMAAIAABVgAo+AkIAAhVIA5AAIAAAKIguAAIAAAbIAsAAIAAAKIgsAAIAAAcIAuAAIAAAKgAppAkIAAgmIgpAAIAAAmIgMAAIAAhVIAMAAIAAAlIApAAIAAglIALAAIAABVgAr8AkIAAhVIAjAAIAOABQAHABADAEQAFAGAAAJQAAARgJADQAFADACAEQACAEABAIQgBASgLAFIgIACIgPAAgArwAaIAYAAIAIgBIAFgCQAEgDAAgIQAAgIgDgDQgCgCgGgBIgNAAIgRAAgArwgMIAZAAIAHgBQABAAAAAAQABAAABgBQAAAAABAAQAAAAAAgBQAEgDAAgIQAAgHgDgDQgCgCgFgBIgNAAIgRAAgAtTAkIAAhVIA5AAIAAAKIguAAIAAAbIAsAAIAAAKIgsAAIAAAcIAuAAIAAAKgAt/AkIAAhLIgoAAIAABLIgMAAIAAhVIBAAAIAABVgAwRAkIAAhVIAjAAIAOABQAHABAEAEQAEAGgBAJQAAARgIADQAFADACAEQADAEgBAIQABASgMAFIgIACIgPAAgAwGAaIAZAAIAIgBIAFgCQAEgDAAgIQAAgIgCgDQgDgCgFgBIgOAAIgSAAgAwGgMIAZAAIAIgBQABAAAAAAQABAAABgBQAAAAABAAQAAAAAAgBQAEgDAAgIQAAgHgDgDQgBgCgGgBIgNAAIgSAAg");
	this.shape.setTransform(107.3,12.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol11, new cjs.Rectangle(0,0,215.8,21.6), null);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AowCIIAAgPIg5AAIAAAPIgLAAIAAgZQAGAAADgEQADgDABgFIAPhAIArAAIAABMIAIAAIAAAZgApbBjQgDAJgDADIAoAAIAAhCIgVAAgAjoB1QgIgGAAgNIALAAQAAAJAGACQAEADAMAAQANAAAFgEQAEgDAAgIQAAgGgBgDQgCgEgEgBIgPgBIgKAAIAAgKIAKAAQAMAAAFgDQAEgDAAgIQAAgGgBgCQgCgEgEgBIgOgBQgNAAgFADQgEAEAAAHIgLAAQAAgPAKgGQAIgDAPAAQASAAAIAGQAHAFAAALQAAAJgDAEQgDAFgGADQAHACADAEQADAEAAALQAAANgKAHQgIAEgQABQgSgBgHgFgAlGB1QgHgFgCgLQgCgGAAgRQAAgRACgGQACgLAHgEQAIgGAQAAQAQAAAIAGQAHAEACALIABAXQAAARgBAGQgCALgHAFQgIAFgQABQgQgBgIgFgAk7AuQgEACgCAEQgDADAAAFIgBASIABASQAAAGADADQACAEAEABQAFACAIAAQAIAAAFgCQAEgBACgEQACgDABgGIABgSIgBgSQgBgFgCgEQgCgDgFgCQgEgBgIgBQgJABgEABgAoCB1QgHgFgCgLQgBgGAAgRQAAgRABgGQACgLAHgEQAIgGAQAAQARAAAIAGQAHAEACALIABAXQAAARgCAGQgCALgHAFQgIAFgQABQgQgBgIgFgAn3AuQgEACgCAEQgCADgBAFIgBASIABASQABAGACADQACAEAFABQAEACAIAAQAJAAAEgCQAEgBADgEQACgDABgGIAAgSIAAgSQgBgFgCgEQgDgDgEgCQgFgBgIgBQgIABgFABgAiOB6IAAhXIALAAIAABXgAmpB6IAAhXIAeAAIARABQAIACAEAFQAFAFAAAMQAAALgFAGQgEAFgIABIgRACIgSAAIAAAlgAmdBKIAXAAQAIAAADgCQAGgCAAgKQAAgKgGgDQgDgCgIAAIgXAAgAq2B6IgJgYIgkAAIgJAYIgMAAIAhhXIAMAAIAhBXgArgBYIAdAAIgOgngAsaB6IAAgoIgpAAIAAAoIgLAAIAAhXIALAAIAAAlIApAAIAAglIALAAIAABXgAJjgcQgHgEgCgLQgBgHAAgQQAAgRABgHQACgKAHgFQAIgGAQABQARgBAIAGQAHAFACAKIABAYQAAAQgCAHQgCALgHAEQgIAGgQAAQgQAAgIgGgAJuhjQgEACgCAEQgCADgBAGIgBASIABASQABAFACAEQACADAFACQAEABAIAAQAJAAAEgCQAEgBADgDQACgEABgFIAAgSIAAgSQgBgGgCgDQgDgEgEgCQgFgBgIAAQgIAAgFABgAEdgcQgHgEgCgLQgCgHAAgQQAAgRACgHQACgKAHgFQAIgGAQABQAQgBAIAGQAHAFACAKIABAYQAAAQgBAHQgCALgHAEQgIAGgQAAQgQAAgIgGgAEohjQgEACgCAEQgDADAAAGIgBASIABASQAAAFADAEQACADAEACQAFABAIAAQAIAAAFgCQAEgBACgDQACgEABgFIABgSIgBgSQgBgGgCgDQgCgEgFgCQgEgBgIAAQgJAAgEABgAlMghQAFAAADgCQAEgCACgJIAOg/IArAAIAABWIgLAAIAAhNIgWAAIgNA5QgBAGgCADIgEAHQgGAFgMAAgAMpgXIAAhNIgbAAIAAgJIBBAAIAAAJIgbAAIAABNgAK8gXIAAhWIAeAAIARAAQAIACAEAFQAFAGAAALQAAALgFAHQgEAFgIABIgRABIgSAAIAAAlgALIhGIAXAAQAIAAADgCQAGgDAAgKQAAgKgGgDQgDgCgIAAIgXAAgAINgXIAAgHQgLgBgGgCQgHgBgEgDQgFgEgDgIQgCgHAAgKQAAgNADgIQACgFAFgFQAFgDAIgBIAPgBIAAgHIAMAAIAAAHQALAAAGABQAGABAEADQAGAFADAIQACAGAAAMQAAAMgDAHQgDAGgFAEQgEAEgIABIgPACIAAAHgAIZgqIANgBQAFgBACgCQADgDACgFQABgEAAgJQAAgJgBgEQgCgFgDgDQgCgCgFgBIgNgBgAIAhbQgEABgCABQgEADgCAFQgBAFAAAKQAAAJABAFQACAEAEACQAEAEAPAAIAAgyIgNABgAHAgXIAAhFIgaBFIgLAAIgahFIAABFIgLAAIAAhWIAPAAIAbBIIAchIIAPAAIAABWgADtgXIgmglIAAAlIgMAAIAAhWIAMAAIAAAkIAogkIAPAAIgvArIAwArgABogXIAAhEIgpBEIgMAAIAAhWIALAAIAABDIAohDIAMAAIAABWgAAJgXIAAhEIgoBEIgMAAIAAhWIALAAIAABDIAnhDIAMAAIAABWgAhWgXIAAgnIgpAAIAAAnIgLAAIAAhWIALAAIAAAkIApAAIAAgkIALAAIAABWgAjlgXIAAhWIAMAAIAAAkIASAAIASABQAIACAEAFQAEAFAAAMQAAAMgEAFQgEAGgIABIgSABgAjZgiIAXAAQAIAAAEgBQAGgDAAgKQAAgJgGgEQgEgBgIAAIgXAAgAllgXIgJgYIgkAAIgJAYIgMAAIAihWIALAAIAiBWgAmOg5IAdAAIgPgngAnJgXIAAhWIAMAAIAABWgAn0gXIAAhFIgaBFIgLAAIgahFIAABFIgLAAIAAhWIAPAAIAcBIIAchIIAOAAIAABWgAqVgXIAAhWIA5AAIAAAJIgtAAIAAAbIAsAAIAAALIgsAAIAAAcIAtAAIAAALgArvgXIAAhWIAeAAIARAAQAIACAEAFQAFAGAAALQAAALgFAHQgEAFgIABIgRABIgSAAIAAAlgArjhGIAXAAQAIAAADgCQAGgDAAgKQAAgKgGgDQgDgCgIAAIgXAAgAsagXIAAhNIgpAAIAABNIgLAAIAAhWIA/AAIAABWgABEh7QgEgDAAgKIAIAAQAAAGACACQACABAHAAQAGAAACgBQACgCAAgGIAIAAQAAALgEADQgEADgKAAQgLAAgEgEg");
	this.shape.setTransform(89.825,1.05);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol7, new cjs.Rectangle(2,-17,176,36.1), null);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0C121C").s().p("AGMCEQgHgGgDgLQgBgGAAgRQAAgRABgGQACgMAIgEQAIgHARAAQASAAAIAHQAHAEADAMQABAGAAAQQAAASgCAHQgCALgHAFQgJAGgQgBQgSAAgIgFgAGYA/QgEADgCAGQgBAGAAAOIABATQACAHAEACQAEADAJAAQAKAAAEgDQAEgCACgGQABgGAAgOIgBgUQgBgGgFgDQgEgCgKAAQgJAAgEACgADMCEQgIgHAAgOIAPAAQAAAGACABQACADAEACIANABQANAAAEgFQAEgCAAgIQAAgFgDgDQgCgCgGAAIgVgBQgMgBgGgEQgHgGAAgOQAAgQAKgFQAIgGARAAQATAAAJAHQAIAGAAANIgPAAQAAgGgEgDQgFgCgMAAQgMAAgEACQgEADAAAHQAAAGADACQACACAGAAIAUABQANABAGAEQAHAGAAAOQAAAPgKAIQgJAFgRAAQgTAAgJgFgAkqCEQgHgGgCgLQgCgGAAgRQAAgRACgGQACgMAHgEQAJgHARAAQARAAAJAHQAHAEACAMQACAGAAAQQAAASgCAHQgCALgIAFQgIAGgRgBQgRAAgJgFgAkeA/QgEADgBAGQgCAGAAAOIABATQACAHAEACQAFADAJAAQAJAAAEgDQAFgCABgGQACgGAAgOIgBgUQgCgGgFgDQgEgCgJAAQgJAAgFACgAmKCEQgHgGgDgLQgBgHAAgQQAAgRABgGQADgLAHgFQAJgHASAAQARAAAIAHQAIAGAAANIgQAAQAAgEgBgDQgCgCgEgBIgMgBQgJAAgEACQgEADgCAGQgBAGAAAOIABATQACAHAEACQAEADAJAAQAMAAAEgDQADgCAAgHIAQAAQAAAQgKAGQgIAFgQgBQgRAAgJgFgAnuCEQgJgHAAgOIAQAAQAAAGACABQACADAEACIAMABQANAAAFgFQADgCAAgIQAAgFgCgDQgCgCgHAAIgUgBQgMgBgGgEQgIgGAAgOQAAgQAKgFQAJgGARAAQATAAAIAHQAJAGAAANIgQAAQAAgGgEgDQgEgCgMAAQgNAAgDACQgEADAAAHQAAAGACACQACACAGAAIAVABQAMABAGAEQAIAGAAAOQAAAPgLAIQgJAFgRAAQgTAAgIgFgAJaCIIAAhKIgbAAIAAgPIBGAAIAAAPIgbAAIAABKgAIcCIIgPgWIgGgJIgDgDIgDgBIgHgBIgEAAIAAAkIgQAAIAAhZIAfAAIATABQAJACAEAFQAFAHAAALQAAALgEAHQgGAHgKACIAZAkgAH2BXIATAAIAKgBQAAAAABAAQABAAAAAAQAAgBABAAQAAAAABgBQADgCAAgIQAAgGgBgDIgFgDIgMAAIgSAAgAEnCIIAAhZIAfAAIATABQAIACAFAFQAFAHAAAMQAAAMgFAGQgEAGgJACQgHABgMAAIgPAAIAAAjgAE3BXIATAAQAJAAADgCQAFgCAAgJQAAgJgFgCIgLgBIgUAAgABbCIIAAgmIgggzIASAAIAWAlIAXglIASAAIghAzIAAAmgAAaCIIgPgWIgGgJIgEgDIgCgBIgGgBIgFAAIAAAkIgQAAIAAhZIAfAAIASABQAJACAEAFQAFAHAAALQAAALgEAHQgFAHgLACIAZAkgAgMBXIATAAIAJgBQABAAAAAAQABAAAAAAQABgBAAAAQABAAAAgBQAEgCAAgIQAAgGgCgDIgFgDIgMAAIgRAAgAh0CIIAAhZIA9AAIAAAPIguAAIAAAWIAtAAIAAAOIgtAAIAAAZIAuAAIAAANgAi5CIIghhZIARAAIAYBGIAZhGIARAAIgiBZgAohCIIAAhZIAQAAIAABZgAqECIIAAhZIAhAAQAOAAAHAEQAHACAFAHQADAFABAIIABATIgBAUQgBAHgDAGQgFAGgJAEQgHABgMAAgAp1B7IARAAQALAAADgCQAGgCACgGQACgGAAgPQAAgOgCgHQgCgGgGgCIgOgBIgRAAgAoagZQgHgFgCgMQgCgHAAgQQAAgQACgIQACgKAHgGQAJgFARAAQARAAAJAFQAHAGACAKQACAHAAARQAAAQgCAIQgCALgIAFQgIAGgRAAQgRgBgJgFgAoOheQgEADgBAFQgCAHAAAOIABAUQACAGAEADQAFACAJAAQAJAAAEgCQAFgCABgHQACgGAAgOIgBgUQgCgGgFgDQgEgCgJgBQgJABgFACgAjJgUIAAhBIglBBIgRAAIAAhZIAPAAIAAA/IAlg/IAQAAIAABZgAkqgUIAAhBIglBBIgRAAIAAhZIAPAAIAAA/IAlg/IAQAAIAABZgAnAgUIAAhZIAgAAIARAAQAJABAEAEQAGAGAAALQAAAJgCAFQgCAEgEACQAFADACAEQACAEAAAJQAAAOgHAGQgEAEgFABQgGACgJAAgAmwgjIATAAQAKAAADgBQABAAAAgBQABAAAAAAQABgBAAAAQABgBAAgBQABgCAAgEQAAgIgDgCIgEgDIgPAAIgPAAgAmwhJIAUAAQAJAAADgCQAEgCAAgIQAAgFgCgCQgDgDgFgBIgLAAIgPAAgApQgUIAAgnIgkAAIAAAnIgQAAIAAhZIAQAAIAAAkIAkAAIAAgkIAQAAIAABZgAjth8QgDgDAAgJIAJAAQAAAEACACQADACAFAAQAGAAACgCQADgCAAgEIAJAAQAAAKgFAEQgEADgLAAQgLAAgFgFg");
	this.shape.setTransform(67.775,18.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol6, new cjs.Rectangle(0,0,135.9,38.4), null);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.b14();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol5, new cjs.Rectangle(0,0,336,280), null);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.b12();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol3, new cjs.Rectangle(0,0,336,280), null);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.b11();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol2, new cjs.Rectangle(0,0,336,280), null);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A2dTiQg+AAAAgwMAAAgliQAAgxA+AAMAs7AAAQA+AAAAAxMAAAAliQAAAwg+AAg");
	this.shape.setTransform(149.975,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(0,0,300,250), null);


(lib.Symbol12_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// leg
	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#0C121C").s().p("AgFAGQgCgCAAgEQAAgHAHAAQAIAAAAAHQAAAIgIAAQgDAAgCgCg");
	this.shape_18.setTransform(271.175,155.525);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#0C121C").s().p("AgZAdQgFgEgBgIIgBgRQAAgLABgHQACgGAEgEQAIgIARAAQASAAAIAIQAEAFACAHIABAQQAAAMgBAHQgCAGgEAEQgIAJgSgBQgRABgIgJgAgNgWQgEACgCAGIgBAOIABAPQACAGAEADQAEACAJAAQAJAAAFgCQAEgDABgGIABgPIgBgOQgBgGgEgCQgFgDgJAAQgJAAgEADg");
	this.shape_19.setTransform(265.325,152.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#0C121C").s().p("AgaAkIAAhHIA1AAIAAALIgpAAIAAA8g");
	this.shape_20.setTransform(258.4,152.625);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#0C121C").s().p("AgZAdQgFgEgBgIIgBgRQAAgLABgHQACgGAEgEQAIgIARAAQASAAAIAIQAEAFACAHIABAQQAAAMgBAHQgCAGgEAEQgIAJgSgBQgRABgIgJgAgNgWQgEACgCAGIgBAOIABAPQACAGAEADQAEACAJAAQAJAAAFgCQAEgDABgGIABgPIgBgOQgBgGgEgCQgFgDgJAAQgJAAgEADg");
	this.shape_21.setTransform(250.475,152.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0C121C").s().p("AASAkIAAggIgjAAIAAAgIgNAAIAAhHIANAAIAAAdIAjAAIAAgdIANAAIAABHg");
	this.shape_22.setTransform(242.2,152.625);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#0C121C").s().p("AASAkIAAggIgjAAIAAAgIgNAAIAAhHIANAAIAAAdIAjAAIAAgdIANAAIAABHg");
	this.shape_23.setTransform(234,152.625);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#0C121C").s().p("AgbAbQgEgJAAgRQAAgMACgHQACgJAHgFQAHgEANAAQAPAAAHAFQAGAFADAJQABAHAAAPIgzAAQAAAIACAEQABAFAFADQAEABAIABQAIgBAFgBQAFgDAAgGIAMAAQAAAVgeAAQgUABgIgLgAgPgTQgDAEAAAJIAmAAQAAgHgCgEQgCgFgDgBQgFgCgIgBQgLAAgEAHg");
	this.shape_24.setTransform(225.9,152.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#0C121C").s().p("AAaAtIAAgSIgzAAIAAASIgMAAIAAgdQAKAAADgNIAMgvIAqAAIAAA8IAIAAIAAAdgAgMAEIgCAIIgEAEIAjAAIAAgxIgTAAg");
	this.shape_25.setTransform(217.525,153.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#0C121C").s().p("AgRAzIAMgeIgbhGIANAAIATA4IAUg4IANAAIgkBkg");
	this.shape_26.setTransform(210.05,154.05);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#0C121C").s().p("AgYAtQgEgEgCgGQgBgHAAgMIAAgcQgBgIACgGQACgGAEgEQAEgEAEgCQAFgCAJAAIAKgCQAGgCAAgEIAMAAQABAJgFAEQgEAFgRABQgLAAgEAFQgEADAAAHIgBAFQAFgEAEgCQAGgCAIAAQASAAAHAMQADAIAAAQQAAANgBAGQgCAHgEAEQgHAIgSAAQgQAAgIgIgAgKgHQgEACgDAFQgCAFAAALIABAOQACAGAEADQAEACAIAAQAJAAAFgCQADgDABgGIACgPIgBgMQgBgEgCgDQgEgFgKAAQgIAAgEACg");
	this.shape_27.setTransform(202.4,151.075);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#0C121C").s().p("AgKAdQgEgDgBgGQgCgGAAgJIgSAAIAAAfIgMAAIAAhHIAMAAIAAAdIASAAIACgNQABgGAEgDQAIgIARAAQASAAAIAIQAEAFACAHIABAQQAAAMgBAHQgCAGgEAEQgIAJgSgBQgRABgIgJgAABgWQgDACgBAGQgCAFAAAJQAAAKACAFQABAGADADQAFACAJAAQAKAAAEgCQAEgDABgGIABgPIgBgOQgBgGgEgCQgFgDgJAAQgJAAgFADg");
	this.shape_28.setTransform(188.925,152.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#0C121C").s().p("AgZAdQgFgEgBgIIgBgRQAAgLABgHQACgGAEgEQAIgIARAAQASAAAIAIQAEAFACAHIABAQQAAAMgBAHQgCAGgEAEQgIAJgSgBQgRABgIgJgAgNgWQgEACgCAGIgBAOIABAPQACAGAEADQAEACAJAAQAJAAAFgCQAEgDABgGIABgPIgBgOQgBgGgEgCQgFgDgJAAQgJAAgEADg");
	this.shape_29.setTransform(178.875,152.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#0C121C").s().p("AAkAkIgeghIAAAhIgLAAIAAghIgeAhIgQAAIAjgkIgjgjIAQAAIAeAfIAAgfIALAAIAAAfIAegfIAPAAIgiAjIAjAkg");
	this.shape_30.setTransform(169.425,152.625);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#0C121C").s().p("AgaAbQgFgJAAgRQAAgMACgHQADgJAGgFQAIgEAMAAQAPAAAHAFQAGAFACAJQACAHAAAPIgyAAQgBAIACAEQACAFAEADQAEABAHABQAKgBADgBQAGgDAAgGIAMAAQAAAVgfAAQgUABgGgLgAgPgTQgDAEAAAJIAlAAQABgHgCgEQgBgFgFgBQgEgCgIgBQgLAAgEAHg");
	this.shape_31.setTransform(160.15,152.6);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#0C121C").s().p("AAbAkIAAgzIgVAzIgLAAIgWgzIAAAzIgMAAIAAhHIAQAAIAXA4IAYg4IAQAAIAABHg");
	this.shape_32.setTransform(151.075,152.625);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#0C121C").s().p("AgZAgQgGgFAAgMQAAgPALgDQAGgEANAAIAUAAIAAgKQgBgEgEgCQgEgCgJAAQgIAAgEACQgFADgBAFIgMAAQAAgMAKgGQAJgDAMAAQAVAAAGALIADAHIAAALIAAArIgMAAIAAgHQgDAFgGABQgHACgHAAQgPABgHgGgAgPAGQgDACAAAHQAAAHAEACQAEADAJAAQAIAAAGgDQAEgCABgGIABgOIgUAAQgKAAgEAEg");
	this.shape_33.setTransform(138.3,152.6);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#0C121C").s().p("AgXAhQgIgGAAgLIAMAAQAAAGAHADIAMABQALAAAEgCQAEgDAAgFQAAgGgBgCQgCgCgEAAIgMgBIgHAAIAAgLIAHAAQALAAAEgCQAEgBAAgHQAAgFgFgCQgEgCgKAAQgKAAgEACQgFADAAAGIgMAAQAAgNAKgGQAIgDAMAAQASAAAHAFQAIAEAAALQAAAFgCAEQgCAFgFACQAFAAACAFQACADAAAIQAAAMgKAGQgIADgPAAQgPABgHgFg");
	this.shape_34.setTransform(130.375,152.6);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#0C121C").s().p("AgZAdQgFgEgBgIIgBgRQAAgLABgHQACgGAEgEQAIgIARAAQASAAAIAIQAEAFACAHIABAQQAAAMgBAHQgCAGgEAEQgIAJgSgBQgRABgIgJgAgNgWQgEACgCAGIgBAOIABAPQACAGAEADQAEACAJAAQAJAAAFgCQAEgDABgGIABgPIgBgOQgBgGgEgCQgFgDgJAAQgJAAgEADg");
	this.shape_35.setTransform(122.225,152.6);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#0C121C").s().p("AAXAyIAAhXIgtAAIAABXIgOAAIAAhjIBJAAIAABjg");
	this.shape_36.setTransform(113.125,151.25);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#0C121C").s().p("AgFAGQgCgCAAgEQAAgHAHAAQAIAAAAAHQAAAIgIAAQgDAAgCgCg");
	this.shape_37.setTransform(102.975,155.525);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#0C121C").s().p("AgFAkIAAg8IgaAAIAAgLIA/AAIAAALIgaAAIAAA8g");
	this.shape_38.setTransform(97.925,152.625);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#0C121C").s().p("AggAzIAAhkIANAAIAAAHQAHgIAPAAQAMAAAIAFQAFAEACAJQADAHAAANQAAALgDAGQgCAJgFAEQgIAGgNAAQgNAAgIgIIAAAjgAgKgkQgFACgCAGQgCAFAAAKQAAALACAEQACAGAFACQAFACAHAAQAMAAADgHQADgFgBgNIgBgMQAAgFgCgDQgEgFgKAAQgHAAgFACg");
	this.shape_39.setTransform(90.5,153.975);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#0C121C").s().p("AgZAdQgFgEgBgIIgBgRQAAgLABgHQACgGAEgEQAIgIARAAQASAAAIAIQAEAFACAHIABAQQAAAMgBAHQgCAGgEAEQgIAJgSgBQgRABgIgJgAgNgWQgEACgCAGIgBAOIABAPQACAGAEADQAEACAJAAQAJAAAFgCQAEgDABgGIABgPIgBgOQgBgGgEgCQgFgDgJAAQgJAAgEADg");
	this.shape_40.setTransform(82.025,152.6);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#0C121C").s().p("AASAkIAAg8IgjAAIAAA8IgMAAIAAhHIA7AAIAABHg");
	this.shape_41.setTransform(73.75,152.625);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#0C121C").s().p("AgZAsQgIgFgDgNQgBgHAAgTQAAgSABgIQADgMAIgGQAJgGASAAQAUAAAIAHQAIAGAAAPIgNAAQAAgGgCgEQgCgDgFgBQgFgCgKAAQgLAAgGAEQgFADgCAKQgBAFAAAQQAAARABAGQACAJAFADQAGAEALAAQAPAAAFgEQAEgDAAgJIANAAQAAAQgKAHQgJAFgRAAQgSAAgJgHg");
	this.shape_42.setTransform(64.875,151.25);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#0C121C").s().p("AgGAzIAAhIIAMAAIAABIgAgFgkQgCgCAAgEQAAgEACgBQACgDADAAQADAAADADQACABAAAEQAAAEgCACQgDABgDAAQgDAAgCgBg");
	this.shape_43.setTransform(301.9,134.95);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#0C121C").s().p("AggAzIAAhkIANAAIAAAHQAHgIAPAAQAMAAAIAFQAFAEACAJQADAHAAANQAAALgDAGQgCAJgFAEQgIAGgNAAQgNAAgIgIIAAAjgAgKgkQgFACgCAGQgCAFAAAKQAAALACAEQACAGAFACQAFACAHAAQAMAAADgHQADgFgBgNIgBgMQAAgFgCgDQgEgFgKAAQgHAAgFACg");
	this.shape_44.setTransform(296.15,137.725);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#0C121C").s().p("AgaAaQgFgIAAgRQAAgMACgHQADgJAGgEQAIgFAMgBQAOAAAIAGQAGAFACAKQACAGAAAPIgyAAQAAAIABAEQABAFAFACQAEACAIAAQAJAAADgCQAGgCAAgHIAMAAQAAAXgeAAQgVAAgGgMgAgPgUQgDAFAAAKIAlAAQAAgIgBgEQgBgFgFgBQgEgCgIAAQgLAAgEAFg");
	this.shape_45.setTransform(287.85,136.35);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#0C121C").s().p("AgeAkIAAhHIAeAAIAOAAIAHABQAJAEAAANQAAAOgIADQAFABACADQACAEAAAHQAAALgGAFQgEAEgIABIgNAAgAgSAZIATAAQAKAAADgBQAEgCAAgHQAAgGgDgCIgEgCIgLgBIgSAAgAgSgGIATAAIAJAAIAFgBQACgDAAgFQAAgFgCgCQgDgCgIAAIgWAAg");
	this.shape_46.setTransform(279.9,136.375);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#0C121C").s().p("AgYAgQgHgFAAgMQAAgPAKgEQAHgDANAAIAVAAIgBgLQgBgEgEgBQgEgCgJAAQgIAAgEACQgGADABAGIgNAAQAAgOALgEQAHgFANAAQAWAAAFAMIACAHIABALIAAAsIgLAAIAAgHQgEADgGACQgHADgHAAQgPAAgGgGgAgPAFQgDADAAAHQAAAGAEADQAEADAIAAQAKAAAEgDQAFgDACgFIABgNIgWAAQgJAAgEACg");
	this.shape_47.setTransform(271.55,136.35);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#0C121C").s().p("AAOAkIgggiIAAAiIgNAAIAAhHIANAAIAAAcIAggcIASAAIgnAhIAnAmg");
	this.shape_48.setTransform(264.45,136.375);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#0C121C").s().p("AgaAZQgDgEgBgJIAAgMQAAgLABgIQADgIAHgEQAHgFANgBQAeABAAAWIgMAAQAAgHgHgCQgDgCgIAAQgIAAgEADQgEADgCAGIgBANIABAOQACAHAEACQAEADAIAAQAJAAAEgCQAFgDAAgGIAMAAQAAAXgeAAQgUAAgHgNg");
	this.shape_49.setTransform(256.325,136.35);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#0C121C").s().p("AgFAzIAAhIIALAAIAABIgAgEgkQgCgCAAgEQAAgEACgBQACgDACAAQADAAACADQACABAAAEQAAAEgCACQgCABgDAAQgCAAgCgBg");
	this.shape_50.setTransform(250.65,134.95);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#0C121C").s().p("AAhA7IAAgSIhBAAIAAASIgNAAIAAgeQAIAAADgEQADgDABgHIAShJIAxAAIAABXIAJAAIAAAegAgQAPQgDALgEADIAuAAIAAhLIgYAAg");
	this.shape_51.setTransform(243.75,135.875);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#0C121C").s().p("AgFAGQgCgCAAgEQAAgHAHAAQAIAAAAAHQAAAIgIAAQgDAAgCgCg");
	this.shape_52.setTransform(237.375,139.275);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#0C121C").s().p("AgfAzIAAhkIALAAIAAAHQAIgIAPAAQAMAAAIAFQAFAEADAJQACAHgBANQABALgCAGQgDAJgFAEQgIAGgNAAQgOAAgHgIIAAAjgAgKgkQgFACgCAGQgCAFAAAKQAAALACAEQACAGAFACQAEACAIAAQAMAAADgHQADgFAAgNIgCgMQAAgFgCgDQgEgFgKAAQgIAAgEACg");
	this.shape_53.setTransform(231.65,137.725);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#0C121C").s().p("AgbAaQgEgIAAgRQAAgMACgHQADgJAGgEQAIgFAMgBQAPAAAHAGQAGAFADAKQABAGAAAPIgzAAQABAIABAEQACAFAEACQAEACAHAAQAJAAAFgCQAFgCAAgHIAMAAQAAAXgfAAQgTAAgIgMgAgPgUQgDAFAAAKIAlAAQAAgIgBgEQgBgFgEgBQgFgCgIAAQgLAAgEAFg");
	this.shape_54.setTransform(223.35,136.35);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#0C121C").s().p("AgeAkIAAhHIAeAAIANAAIAHABQAKAEAAANQAAAOgIADQAFABACADQACAEAAAHQAAALgFAFQgFAEgIABIgNAAgAgRAZIASAAQAJAAADgBQAFgCAAgHQAAgGgCgCIgGgCIgKgBIgRAAgAgRgGIASAAIAJAAIAFgBQACgDABgFQgBgFgCgCQgDgCgIAAIgVAAg");
	this.shape_55.setTransform(215.4,136.375);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#0C121C").s().p("AgZAeQgFgFgBgIIgBgRQAAgMABgGQACgHAEgDQAIgJARAAQASAAAIAJQAEAFACAHIABAQQAAANgBAGQgCAGgEAFQgIAHgSABQgRgBgIgHgAgNgWQgEADgCAGIgBANIABAOQACAHAEACQAEADAJAAQAJAAAFgDQAEgCABgHIABgOIgBgNQgBgGgEgDQgFgDgJAAQgJAAgEADg");
	this.shape_56.setTransform(207.075,136.35);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#0C121C").s().p("AgkAyIAAhjIAiAAIAUABQAJACAFAGQAFAGAAANQAAAOgFAGQgFAGgJABQgHABgNAAIgUAAIAAArgAgWgDIAUAAIAFAAQAKAAAEgCQAGgEAAgMQAAgLgGgDQgEgCgKAAIgFAAIgUAAg");
	this.shape_57.setTransform(198.575,135);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#0C121C").s().p("AAaAtIAAgSIgzAAIAAASIgMAAIAAgdQAKAAADgMIAMgwIAqAAIAAA8IAIAAIAAAdgAgMAEIgCAJIgEADIAjAAIAAgxIgTAAg");
	this.shape_58.setTransform(185.775,137.25);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#0C121C").s().p("AASAkIAAggIgjAAIAAAgIgNAAIAAhHIANAAIAAAdIAjAAIAAgdIANAAIAABHg");
	this.shape_59.setTransform(177.75,136.375);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#0C121C").s().p("AgbAaQgEgIAAgRQAAgMACgHQACgJAHgEQAHgFANgBQAPAAAHAGQAGAFADAKQABAGAAAPIgzAAQAAAIACAEQABAFAFACQAEACAIAAQAIAAAFgCQAFgCAAgHIAMAAQAAAXgeAAQgUAAgIgMgAgPgUQgDAFAAAKIAmAAQAAgIgCgEQgCgFgDgBQgFgCgIAAQgLAAgEAFg");
	this.shape_60.setTransform(169.65,136.35);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#0C121C").s().p("AgoAmQAFAAAEgCQAEgDADgKIAQhJIAxAAIAABkIgNAAIAAhXIgaAAIgOA/IgDALQgCAFgDACQgGAGgOABg");
	this.shape_61.setTransform(160.225,135.05);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#0C121C").s().p("AgFAGQgCgCAAgEQAAgHAHAAQAIAAAAAHQAAAIgIAAQgDAAgCgCg");
	this.shape_62.setTransform(150.775,139.275);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#0C121C").s().p("AgXAtQgIgGAAgNIAMAAQAAAIAFADQAEACAJAAQAIAAAEgCQAFgCABgEQADgEAAgJIgBgLIgDgGQgEgEgLAAQgTAAAAALIgMAAIAAg6IA7AAIAAAMIgvAAIAAAdQADgCAFgCQAGgCAFAAQASABAHAIQAGAHAAARQAAATgJAHQgHAGgRABQgPAAgHgGg");
	this.shape_63.setTransform(144.9,135.05);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#0C121C").s().p("AgXAuQgJgGAAgNIANAAQAAAIAFACQAFACAJABQALAAAFgFQAEgDAAgKQAAgJgBgDQgCgDgEgCIgNgBIgOAAIAAgKIAOAAIAKgBIAFgDQAEgDAAgJQAAgHgBgDQgCgDgEgCQgEgBgIgBQgLAAgEADQgEAEAAAFIgNAAQAAgOAKgFQAIgEAOAAQASAAAHAHQAHAGAAAOQAAAJgCAEQgCAGgGACQAGACACAFQADAFAAALQAAARgKAIQgIAFgPAAQgPAAgIgFg");
	this.shape_64.setTransform(136.425,135);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#0C121C").s().p("AgYAtQgHgGAAgNIAMAAQAAAIAFADQAEACAKAAQAHAAAEgCQAFgCACgEQACgEAAgJIgBgLIgDgGQgEgEgLAAQgTAAABALIgNAAIAAg6IA7AAIAAAMIguAAIAAAdQACgCAGgCQAFgCAFAAQASABAIAIQAFAHAAARQAAATgJAHQgIAGgPABQgQAAgIgGg");
	this.shape_65.setTransform(128.1,135.05);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#0C121C").s().p("AAIAyIAAgbIgrAAIAAgLIArg9IANAAIAAA9IAOAAIAAALIgOAAIAAAbgAgUAMIAcAAIAAgqg");
	this.shape_66.setTransform(119.6,135);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#0C121C").s().p("AgYAtQgHgGAAgNIAMAAQAAAIAFADQAEACAKAAQAHAAAEgCQAEgCACgEQACgEAAgJIgBgLIgCgGQgEgEgMAAQgRAAgBALIgMAAIAAg6IA7AAIAAAMIgvAAIAAAdQADgCAGgCQAEgCAGAAQASABAHAIQAGAHAAARQAAATgJAHQgHAGgQABQgQAAgIgGg");
	this.shape_67.setTransform(111.2,135.05);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#0C121C").s().p("AgWAtQgGgFgDgKQgCgIAAgOIAAgIIAAgGQAAgPACgIQADgKAGgFQAIgGAOAAQAPAAAIAGQAHAFACAKQABAIABAPIAAAGIAAARIgBAIQgCAMgGAHQgJAHgQAAQgOAAgIgGgAgOgiQgEADgBAJIAAAWIAAAXQABAJAEADQAFAFAJAAQAKAAAFgFQAEgDABgJIAAgXIAAgWQgBgJgEgDQgFgFgKAAQgJAAgFAFg");
	this.shape_68.setTransform(102.65,135);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#0C121C").s().p("AgWAtQgHgFgCgKQgCgIABgOIAAgIIAAgGQgBgPACgIQACgKAHgFQAIgGAOAAQAPAAAIAGQAGAFADAKQABAIAAAPIAAAGIAAARIgBAIQgBAMgHAHQgHAHgRAAQgOAAgIgGgAgOgiQgDADgCAJIgBAWIABAXQACAJADADQAFAFAJAAQAKAAAEgFQAFgDABgJIABgXIgBgWQgBgJgFgDQgEgFgKAAQgJAAgFAFg");
	this.shape_69.setTransform(94.15,135);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#0C121C").s().p("AgfAzIAAgYQAAgKAFgHQAEgFAIgDIAPgDIAJgEIAFgDQAEgEAAgIQAAgLgEgEQgEgDgLAAQgKAAgEADQgEADAAAGIgNAAQAAgOAKgFQAIgFANAAQAQABAIAGQAIAGAAARQAAAPgJAGIgHAEIgNAEIgMAFQgFACgCADQgCAEAAAGIAAAKIAyAAIAAAMg");
	this.shape_70.setTransform(85.775,134.95);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#0C121C").s().p("AgbAsQgIgFgCgNQgCgHAAgTQAAgSACgHQACgNAIgFQAJgHASAAQATAAAJAHQAIAFACAMQACAIAAASQAAATgCAIQgCAMgIAFQgJAHgTAAQgSAAgJgHgAgOgkQgFACgCAEQgDADAAAHIgBAUIABAVQAAAGADAEQADAFAFABQAFACAIAAQAKAAAFgCQAFgCACgEQADgEABgGIABgVIgBgUQgBgHgDgDQgDgFgFgBQgFgCgJAAQgJAAgFACg");
	this.shape_71.setTransform(72.975,135);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#0C121C").s().p("AgkAyIAAhjIAiAAIAUABQAJACAFAGQAFAGAAANQAAAOgFAGQgFAGgJABQgHABgNAAIgUAAIAAArgAgWgDIAUAAIAFAAQAKAAAEgCQAGgEAAgMQAAgLgGgDQgEgCgKAAIgFAAIgUAAg");
	this.shape_72.setTransform(63.625,135);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#0C121C").s().p("AAXAyIAAhXIgtAAIAABXIgOAAIAAhjIBJAAIAABjg");
	this.shape_73.setTransform(53.775,135);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#0C121C").s().p("AAhA7IAAgSIhBAAIAAASIgNAAIAAgeQAHAAAEgEQADgDABgHIAShJIAxAAIAABXIAJAAIAAAegAgQAPQgCALgFADIAuAAIAAhLIgYAAg");
	this.shape_74.setTransform(43.65,135.875);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#0C121C").s().p("AgZAsQgIgGgDgMQgBgHAAgTQAAgSABgHQADgNAIgFQAJgHASAAQAUAAAIAHQAIAHAAAOIgNAAQAAgGgCgDQgCgEgFgCQgFgBgKAAQgKAAgGADQgFADgCAIQgCAFAAANIAlAAIAAAKIglAAIABAUQACAJAGACQAFAEALAAQAPAAAFgEQAEgDAAgJIANAAQAAARgKAGQgJAFgRAAQgSAAgJgHg");
	this.shape_75.setTransform(34.175,135);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#0C121C").s().p("AAaAtIAAgSIgzAAIAAASIgMAAIAAgdQAKAAADgNIAMgvIAqAAIAAA8IAIAAIAAAdgAgMAEIgCAIIgEAEIAjAAIAAgxIgTAAg");
	this.shape_76.setTransform(295.575,121);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#0C121C").s().p("AgZAdQgFgEgBgHIgBgSQAAgLABgHQACgHAEgDQAIgIARAAQASAAAIAIQAEAFACAHIABAQQAAAMgBAHQgCAGgEAEQgIAJgSgBQgRABgIgJgAgNgWQgEADgCAFIgBAOIABAPQACAGAEADQAEACAJAAQAJAAAFgCQAEgDABgGIABgPIgBgOQgBgFgEgDQgFgDgJAAQgJAAgEADg");
	this.shape_77.setTransform(287.475,120.1);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#0C121C").s().p("AAOAkIgggiIAAAiIgNAAIAAhHIANAAIAAAcIAggcIASAAIgmAhIAmAmg");
	this.shape_78.setTransform(280.1,120.125);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#0C121C").s().p("AgJAMIAFgGIACgCQACgDgBgFIAAgOIALAAIAAAOIgBAKIgFAIIgFAFg");
	this.shape_79.setTransform(270.25,124.1);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#0C121C").s().p("AABAYIAEgFIAJgKQADgEAAgEQAAgDgCgEQgCgEgGgGIgGgGIAIgIQAKAKAEAFQAHAJAAAHQAAAIgIAJIgNANgAgdAYIAFgFIAIgKQAEgEAAgEQAAgDgCgEQgCgEgHgGIgGgGIAIgIQALAKAEAFQAGAJAAAHQAAAIgIAJIgMANg");
	this.shape_80.setTransform(265.375,120.1);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#0C121C").s().p("AAaAtIAAgSIgzAAIAAASIgMAAIAAgdQAKAAADgNIAMgvIAqAAIAAA8IAIAAIAAAdgAgMAEIgCAIIgEAEIAjAAIAAgxIgTAAg");
	this.shape_81.setTransform(257.475,121);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#0C121C").s().p("AgFAkIAAg8IgaAAIAAgLIA/AAIAAALIgaAAIAAA8g");
	this.shape_82.setTransform(250.175,120.125);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#0C121C").s().p("AgoAnQAFgBAEgCQAEgDADgKIAQhIIAxAAIAABjIgNAAIAAhYIgaAAIgOBAIgDAMQgCADgDADQgGAHgOgBg");
	this.shape_83.setTransform(241.425,118.8);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#0C121C").s().p("AgJAMIAFgGIACgCQACgDAAgFIAAgOIAKAAIAAAOIgBAKIgGAIIgEAFg");
	this.shape_84.setTransform(231.6,124.1);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#0C121C").s().p("AgYAgQgHgFAAgMQAAgPAKgEQAHgDANAAIAVAAIgBgKQgBgEgEgCQgEgCgJAAQgIAAgEACQgGADABAFIgNAAQAAgMALgGQAHgDANAAQAWAAAGALIABAHIABALIAAAsIgMAAIAAgIQgDAFgGACQgHABgHAAQgPAAgGgFgAgOAGQgEACAAAHQAAAHAEACQAEADAIAAQAKAAAEgDQAFgCACgGIABgOIgWAAQgJAAgDAEg");
	this.shape_85.setTransform(226.1,120.1);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#0C121C").s().p("AASAkIAAggIgjAAIAAAgIgNAAIAAhHIANAAIAAAdIAjAAIAAgdIAMAAIAABHg");
	this.shape_86.setTransform(218.1,120.125);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#0C121C").s().p("AgFAyIAAhIIALAAIAABIgAAIgqQAAgEADgBQABgCAEAAQAHAAAAAHQAAAHgHAAQgIAAAAgHgAgWgqQgBgEACgBQACgCAEAAQAHAAAAAHQAAAHgHAAQgIAAABgHg");
	this.shape_87.setTransform(212.3,118.75);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#0C121C").s().p("AgZAgQgGgFAAgMQAAgPAKgEQAHgDANAAIAUAAIAAgKQgBgEgEgCQgEgCgJAAQgIAAgEACQgFADAAAFIgNAAQAAgMALgGQAHgDANAAQAWAAAFALIACAHIABALIAAAsIgMAAIAAgIQgDAFgGACQgGABgIAAQgPAAgHgFgAgPAGQgDACAAAHQAAAHAEACQAEADAJAAQAIAAAFgDQAFgCACgGIAAgOIgUAAQgKAAgEAEg");
	this.shape_88.setTransform(206.4,120.1);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#0C121C").s().p("AgfAzIAAhkIALAAIAAAHQAIgIAPAAQAMAAAHAFQAGAEADAJQABAHAAANQAAALgBAGQgDAJgGAEQgHAGgNAAQgOAAgHgIIAAAjgAgKgkQgFACgCAGQgCAFAAAKQAAALACAEQACAGAFACQAFACAHAAQAMAAADgHQADgFAAgNIgBgMQgBgFgCgDQgEgFgKAAQgHAAgFACg");
	this.shape_89.setTransform(198.45,121.475);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#0C121C").s().p("AAPAkIghgiIAAAiIgNAAIAAhHIANAAIAAAcIAhgcIARAAIgnAhIAnAmg");
	this.shape_90.setTransform(190.95,120.125);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#0C121C").s().p("AgYAyIARghIgjhCIAPAAIAbA0IAbg0IAQAAIg0Bjg");
	this.shape_91.setTransform(182.4,118.75);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#0C121C").s().p("AgaAaQgDgGgBgIIAAgMQAAgLABgHQADgJAHgFQAHgEANAAQAegBAAAXIgMAAQAAgHgHgDQgDgBgIAAQgIAAgEADQgEADgCAFIgBAOIABAPQACAGAEADQAEACAIAAQAJAAAEgCQAFgDAAgFIAMAAQAAAVgeAAQgUABgHgMg");
	this.shape_92.setTransform(170.575,120.1);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#0C121C").s().p("AgFAkIAAg8IgaAAIAAgLIA/AAIAAALIgaAAIAAA8g");
	this.shape_93.setTransform(163.225,120.125);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#0C121C").s().p("AgfAzIAAhkIALAAIAAAHQAIgIAPAAQANAAAGAFQAHAEABAJQACAHAAANQAAALgCAGQgBAJgHAEQgHAGgNAAQgOAAgHgIIAAAjgAgKgkQgFACgCAGQgCAFAAAKQAAALACAEQACAGAFACQAFACAHAAQAMAAADgHQACgFABgNIgBgMQgBgFgCgDQgEgFgKAAQgHAAgFACg");
	this.shape_94.setTransform(155.8,121.475);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#0C121C").s().p("AgZAdQgFgEgBgHIgBgSQAAgLABgHQACgHAEgDQAIgIARAAQASAAAIAIQAEAFACAHIABAQQAAAMgBAHQgCAGgEAEQgIAJgSgBQgRABgIgJgAgNgWQgEADgCAFIgBAOIABAPQACAGAEADQAEACAJAAQAJAAAFgCQAEgDABgGIABgPIgBgOQgBgFgEgDQgFgDgJAAQgJAAgEADg");
	this.shape_95.setTransform(147.325,120.1);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#0C121C").s().p("AASAkIAAg8IgjAAIAAA8IgNAAIAAhHIA9AAIAABHg");
	this.shape_96.setTransform(139.05,120.125);

	this.shape_97 = new cjs.Shape();
	this.shape_97.graphics.f("#0C121C").s().p("AAbAkIAAgzIgVAzIgLAAIgWgzIAAAzIgMAAIAAhHIAQAAIAXA4IAYg4IAQAAIAABHg");
	this.shape_97.setTransform(129.925,120.125);

	this.shape_98 = new cjs.Shape();
	this.shape_98.graphics.f("#0C121C").s().p("AgGAyIAAhjIANAAIAABjg");
	this.shape_98.setTransform(122.975,118.75);

	this.shape_99 = new cjs.Shape();
	this.shape_99.graphics.f("#0C121C").s().p("AggAzIAAhkIANAAIAAAHQAHgIAPAAQAMAAAIAFQAFAEACAJQADAHAAANQAAALgDAGQgCAJgFAEQgIAGgNAAQgNAAgIgIIAAAjgAgKgkQgFACgCAGQgCAFAAAKQAAALACAEQACAGAFACQAFACAHAAQAMAAADgHQADgFgBgNIgBgMQAAgFgCgDQgEgFgKAAQgHAAgFACg");
	this.shape_99.setTransform(113.45,121.475);

	this.shape_100 = new cjs.Shape();
	this.shape_100.graphics.f("#0C121C").s().p("AgaAbQgFgJAAgRQAAgMACgHQADgJAGgFQAIgEAMAAQAOgBAIAGQAGAFACAJQACAIAAANIgyAAQAAAJABAEQABAFAFADQAEACAIAAQAJAAADgCQAGgDAAgGIAMAAQAAAVgeAAQgVABgGgLgAgPgTQgDAEAAAJIAlAAQAAgHgBgEQgBgEgFgCQgEgCgIgBQgLAAgEAHg");
	this.shape_100.setTransform(105.15,120.1);

	this.shape_101 = new cjs.Shape();
	this.shape_101.graphics.f("#0C121C").s().p("AASAkIAAggIgjAAIAAAgIgMAAIAAhHIAMAAIAAAdIAjAAIAAgdIANAAIAABHg");
	this.shape_101.setTransform(97,120.125);

	this.shape_102 = new cjs.Shape();
	this.shape_102.graphics.f("#0C121C").s().p("AASAkIAAggIgjAAIAAAgIgMAAIAAhHIAMAAIAAAdIAjAAIAAgdIANAAIAABHg");
	this.shape_102.setTransform(88.8,120.125);

	this.shape_103 = new cjs.Shape();
	this.shape_103.graphics.f("#0C121C").s().p("AgGAyIAAhHIAMAAIAABHgAgFglQgBgCAAgDQAAgDABgDQACgBADAAQADAAACABQACADABADQgBADgCACQgCACgDAAQgDAAgCgCg");
	this.shape_103.setTransform(83,118.7);

	this.shape_104 = new cjs.Shape();
	this.shape_104.graphics.f("#0C121C").s().p("AgkAyIAAhjIAiAAIAFAAIARABQAIACAEAFQAEAGAAALQAAATgKAFQAGABADAGQACAEAAAKQAAAVgOAFIgIACIgQABgAgXAmIAVAAIAGAAIAKgBIAFgCQAFgDAAgLQAAgIgDgEQgDgDgGgBIgOgBIgVAAgAgXgHIAVAAIAHAAIAJAAIAFgCQAEgDAAgKQAAgHgDgEQgDgDgGAAIgOgBIgUAAg");
	this.shape_104.setTransform(76.525,118.75);

	this.shape_105 = new cjs.Shape();
	this.shape_105.graphics.f("#0C121C").s().p("AAHARQgGgIAAgIQAAgIAIgKIAMgNIAJAIIgHAGIgHAJQgDAFAAADQAAAEAEAFIAIAJIAEAFIgIAHIgOgOgAgXARQgGgIAAgIQAAgIAIgKIANgNIAIAIIgGAGIgIAJQgDAFAAADQAAAEAFAFIAHAJIAFAFIgIAHIgPgOg");
	this.shape_105.setTransform(68.025,120.1);

	this.shape_106 = new cjs.Shape();
	this.shape_106.graphics.f("#0C121C").s().p("AgkAyIAAhjIAiAAIAFAAIARABQAIACAEAFQAEAGAAALQAAATgKAFQAGABADAGQACAEAAAKQAAAVgOAFIgIACIgQABgAgXAmIAVAAIAGAAIAKgBIAFgCQAFgDAAgLQAAgIgDgEQgDgDgGgBIgOgBIgVAAgAgXgHIAVAAIAHAAIAJAAIAFgCQAEgDAAgKQAAgHgDgEQgDgDgGAAIgOgBIgUAAg");
	this.shape_106.setTransform(56.075,118.75);

	this.shape_107 = new cjs.Shape();
	this.shape_107.graphics.f("#0C121C").s().p("AgbAtQgIgGgCgMQgCgIAAgTQAAgSACgIQACgMAIgGQAJgGASAAQATAAAJAGQAIAGACAMQACAIAAASQAAATgCAIQgCAMgIAGQgJAGgTAAQgSAAgJgGgAgOgkQgFACgCAEQgDAEAAAGIgBAUIABAUQAAAHADAEQADAEAFACQAFACAIAAQAKAAAFgCQAFgCACgEQADgEABgHIABgUIgBgUQgBgGgDgEQgDgFgFgBQgFgCgJAAQgJAAgFACg");
	this.shape_107.setTransform(46.025,118.75);

	this.shape_108 = new cjs.Shape();
	this.shape_108.graphics.f("#0C121C").s().p("AgGAyIAAhXIgfAAIAAgMIBLAAIAAAMIgfAAIAABXg");
	this.shape_108.setTransform(36.95,118.75);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_108},{t:this.shape_107},{t:this.shape_106},{t:this.shape_105},{t:this.shape_104},{t:this.shape_103},{t:this.shape_102},{t:this.shape_101},{t:this.shape_100},{t:this.shape_99},{t:this.shape_98},{t:this.shape_97},{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18}]}).wait(1));

	// Layer_1
	this.shape_109 = new cjs.Shape();
	this.shape_109.graphics.f("#FFFFFF").s().p("A9CYQMAAAgweMA6FAAAMAAAAweg");
	this.shape_109.setTransform(170.2,143.35);

	this.timeline.addTween(cjs.Tween.get(this.shape_109).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol12_1, new cjs.Rectangle(-15.7,-11.8,371.8,310.3), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#006537").ss(1,0,0,4).p("AgVgaIAlAbIglAa");
	this.shape.setTransform(2.8291,3.619,1,1.4531);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ7, new cjs.Rectangle(-0.3,-1.3,5.8,9.9), null);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1 copy 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHjAgIAGgOIgOgiIAHAAIAKAbIAJgbIAHAAIgSAwgAgwAgIAAgwIAFAAIAAAEQAEgEAIAAQAGAAADACQADACABAEIABAJIgBAIQgBAFgDACQgDADgHAAQgHAAgEgEIAAARgAgmgKQgCABgBADIgCAHIACAHQABADACABIAGABQAGAAABgDIACgJIAAgFIgCgEQgCgDgFAAIgGABgAh/AgIAAgRQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAIgGABQgJAAgCgGQgCgEAAgIIABgJQABgEACgCQAEgCAFAAQAHAAADADIAAgSIAGAAIAAASQADgDAHAAQAIAAADAFQACAEAAAIIgBAJQgBAEgDACQgDADgGAAIgFgBQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBIAAARgAh2gKQAAABAAAAQgBAAAAABQAAAAgBABQAAAAAAABIgBAHQAAAHACADQADACAEAAQAFAAABgCQACgDAAgHQAAgGgCgDQgBgDgFAAIgGABgAiOgIQgCACAAAHQAAAHABACQACADAFAAIAFgBIADgEIABgHQAAgHgCgDQgCgCgFAAQgFAAgBADgAnKAgIAAgwIAGAAIAAAEQAEgEAHAAQAGAAADACQADACACAEIABAJIgBAIQgCAFgDACQgDADgHAAQgGAAgEgEIAAARgAnAgKQgCABgBADIgBAHIABAHQABADACABIAGABQAGAAACgDIABgJIAAgFIgBgEQgDgDgFAAIgGABgABqAbIAAgJIgcAAIAAgiIAHAAIAAAdIARAAIAAgdIAGAAIAAAdIAEAAIAAAOgAEKANQgCgCAAgEIAAgGIABgJQAAgEAEgCQADgCAHAAQAPAAAAAKIgGAAQAAgDgDgBIgGgBIgGABQgCACgBADIgBAGIABAHQABADACABQACABAEAAIAGgBQABAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAGAAQAAALgPAAQgKAAgDgGgAApAQQgDgDAAgFQAAgHAFgCQADgBAGAAIALAAIgBgFQAAgBAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBIgGABQgDABAAADIgGAAQAAgGAFgDQAEgBAGAAQALAAADAFIABADIAAAGIAAAUIgGAAIAAgDQgBACgDABIgIABQgGAAgEgDgAAuADQAAAAgBABQAAAAAAABQgBAAAAABQAAABAAABQAAABAAAAQAAABABABQAAAAAAABQABAAAAAAQACACAEAAQAFAAADgCQAAAAAAAAQABgBAAAAQAAgBABAAQAAgBAAgBIABgGIgLAAQgFAAgBABgAhWAPQgCgCgBgEIgBgIIABgIQABgEACgBQAEgEAIAAQAKAAADAEQACACABADIABAIIgBAJQgBADgCACQgDAEgKAAQgIAAgEgEgAhQgJQgCABgBADIAAAGIAAAHQABADACABQACABAEAAQAFAAADgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAgBAAAAIAAgHIAAgGQAAgDgCgCIgIgBQgEAAgCACgAkEAQQgDgDAAgFQAAgHAGgCQADgBAGAAIALAAIgBgFQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAIgFgBIgHABQgDABABADIgHAAQAAgGAGgDQADgBAHAAQAKAAADAFIABADIAAAGIAAAUIgFAAIAAgDQgCACgDABIgHABQgHAAgEgDgAj+ADQgBAAAAABQgBAAAAABQAAAAAAABQAAABAAABQAAABAAAAQAAABAAABQAAAAABABQAAAAABAAQABACAFAAQAFAAACgCQABAAAAAAQAAgBABAAQAAgBAAAAQAAgBABgBIABgGIgLAAQgFAAgBABgAlRAPQgCgCgBgEIgBgIIABgIQABgEACgBQAEgEAIAAQAKAAADAEQACACABADIABAIIgBAJQgBADgCACQgDAEgKAAQgIAAgEgEgAlLgJQgCABgBADIgBAGIABAHQABADACABQACABAEAAQAFAAADgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAgBAAAAIAAgHIAAgGQAAgDgCgCIgIgBQgEAAgCACgAmgAQQgDgDAAgFQAAgHAFgCQADgBAGAAIALAAIgBgFQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAIgGgBIgGABQgDABAAADIgGAAQAAgGAFgDQAEgBAGAAQALAAADAFIAAADIABAGIAAAUIgGAAIAAgDQgBACgDABIgIABQgGAAgEgDgAmbADQAAAAgBABQAAAAAAABQgBAAAAABQAAABAAABQAAABAAAAQAAABABABQAAAAAAABQABAAAAAAQACACAEAAQAFAAACgCQABAAAAAAQABgBAAAAQAAgBABAAQAAgBAAgBIABgGIgLAAQgFAAgBABgAIKASIAAgdIgMAAIAAgFIAeAAIAAAFIgMAAIAAAdgAHHASIAAgdIgNAAIAAgFIAfAAIAAAFIgMAAIAAAdgAGZASIgSAAIAAgiIAGAAIAAAPIAMAAIAFAAIAEABQACACAAAGQAAAGgCACIgDABIgEABIgCAAgAGNANIAJAAIAFAAIABgBQABAAAAAAQAAgBABAAQAAgBAAgBQAAAAAAgBIgBgEIgCgBIgFAAIgJAAgAFvASIAAgdIgMAAIAAgFIAeAAIAAAFIgMAAIAAAdgAFWASIAAgiIAGAAIAAAigAFGASIAAgPIgRAAIAAAPIgGAAIAAgiIAGAAIAAAPIARAAIAAgPIAGAAIAAAigAD5ASIAAgZIgSAZIgGAAIAAgiIAGAAIAAAZIARgZIAHAAIAAAigADJASIAAgdIgNAAIAAgFIAfAAIAAAFIgNAAIAAAdgACfASIAAgPIgDAAIgEABIgCAAIAAABIgDAEIgGAJIgHAAIAKgPQgGAAgBgDQgCgBAAgFQAAgGAFgDIAJgBIAQAAIAAAigACRgKIgCAAQAAABgBAAQAAAAAAABQAAAAAAABQgBAAAAABQAAABABABQAAABAAAAQAAABABAAQAAAAAAABIAGAAIAKAAIAAgKIgJAAIgFABgAB4ASIAAgiIAFAAIAAAigAAYASIAAgYIgLAYIgGAAIgJgYIAAAYIgGAAIAAgiIAIAAIAKAbIAMgbIAIAAIAAAigAilASIAAgPIgRAAIAAAPIgHAAIAAgiIAHAAIAAAPIARAAIAAgPIAGAAIAAAigAjNASIAAgiIAGAAIAAAigAkcASIgPAAIAAgiIAOAAIAHAAIAEABQAEACAAAGQAAAHgDAAIACADIABAFQABAFgDADQgDACgDAAIgGAAgAklANIAJAAIAGgBQABAAAAAAQAAgBABAAQAAgBAAgBQAAAAAAgBIgBgEIgDgBIgFAAIgIAAgAklgBIAJAAIAEAAIADgBIABgEQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBgBQgBgBgDAAIgLAAgAlrASIgQAAIAAgiIAPAAIAHAAIAEABQAEACAAAGQAAAHgEAAIADADIABAFQAAAFgCADQgDACgDAAIgGAAgAl0ANIAJAAIAGgBQAAAAABAAQAAgBAAAAQABgBAAgBQAAAAAAgBIgBgEIgDgBIgFAAIgIAAgAl0gBIAJAAIAEAAIADgBIABgEQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQgCgBgEAAIgKAAgAnbASIAAgdIgRAAIAAAdIgGAAIAAgiIAdAAIAAAigAoKgIIgIAKIgEgCIAIgLIgOgEIACgFIAOAEIAAgNIAEAAIAAANIAOgEIACAFIgNAEIAIALIgFACgAFWgXIgBgDIABgDIADgBIADABIAAADIAAADIgDABIgDgBgAB4gXIgBgDIABgDIADgBIACABIABADIgBADIgCABIgDgBgAjMgXIgBgDIABgDIADgBIACABIABADIgBADIgCABIgDgBg");
	this.shape.setTransform(-79.4,13.925);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer 1 copy
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AHjAgIAGgOIgOgiIAHAAIAKAbIAJgbIAHAAIgSAwgAgwAgIAAgwIAFAAIAAAEQAEgEAIAAQAGAAADACQADACABAEIABAJIgBAIQgBAFgDACQgDADgHAAQgHAAgEgEIAAARgAgmgKQgCABgBADIgCAHIACAHQABADACABIAGABQAGAAABgDIACgJIAAgFIgCgEQgCgDgFAAIgGABgAh/AgIAAgRQAAABgBAAQAAABgBAAQAAAAgBAAQAAABgBAAIgGABQgJAAgCgGQgCgEAAgIIABgJQABgEACgCQAEgCAFAAQAHAAADADIAAgSIAGAAIAAASQADgDAHAAQAIAAADAFQACAEAAAIIgBAJQgBAEgDACQgDADgGAAIgFgBQgBAAAAgBQgBAAAAAAQgBAAAAgBQgBAAAAgBIAAARgAh2gKQAAABAAAAQgBAAAAABQAAAAgBABQAAAAAAABIgBAHQAAAHACADQADACAEAAQAFAAABgCQACgDAAgHQAAgGgCgDQgBgDgFAAIgGABgAiOgIQgCACAAAHQAAAHABACQACADAFAAIAFgBIADgEIABgHQAAgHgCgDQgCgCgFAAQgFAAgBADgAnKAgIAAgwIAGAAIAAAEQAEgEAHAAQAGAAADACQADACACAEIABAJIgBAIQgCAFgDACQgDADgHAAQgGAAgEgEIAAARgAnAgKQgCABgBADIgBAHIABAHQABADACABIAGABQAGAAACgDIABgJIAAgFIgBgEQgDgDgFAAIgGABgABqAbIAAgJIgcAAIAAgiIAHAAIAAAdIARAAIAAgdIAGAAIAAAdIAEAAIAAAOgAEKANQgCgCAAgEIAAgGIABgJQAAgEAEgCQADgCAHAAQAPAAAAAKIgGAAQAAgDgDgBIgGgBIgGABQgCACgBADIgBAGIABAHQABADACABQACABAEAAIAGgBQABAAABAAQAAgBAAAAQABgBAAAAQAAgBAAgBIAGAAQAAALgPAAQgKAAgDgGgAApAQQgDgDAAgFQAAgHAFgCQADgBAGAAIALAAIgBgFQAAgBAAAAQAAgBAAAAQgBAAAAgBQgBAAAAAAIgGgBIgGABQgDABAAADIgGAAQAAgGAFgDQAEgBAGAAQALAAADAFIABADIAAAGIAAAUIgGAAIAAgDQgBACgDABIgIABQgGAAgEgDgAAuADQAAAAgBABQAAAAAAABQgBAAAAABQAAABAAABQAAABAAAAQAAABABABQAAAAAAABQABAAAAAAQACACAEAAQAFAAADgCQAAAAAAAAQABgBAAAAQAAgBABAAQAAgBAAgBIABgGIgLAAQgFAAgBABgAhWAPQgCgCgBgEIgBgIIABgIQABgEACgBQAEgEAIAAQAKAAADAEQACACABADIABAIIgBAJQgBADgCACQgDAEgKAAQgIAAgEgEgAhQgJQgCABgBADIAAAGIAAAHQABADACABQACABAEAAQAFAAADgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAgBAAAAIAAgHIAAgGQAAgDgCgCIgIgBQgEAAgCACgAkEAQQgDgDAAgFQAAgHAGgCQADgBAGAAIALAAIgBgFQAAgBAAAAQgBgBAAAAQAAAAgBgBQAAAAgBAAIgFgBIgHABQgDABABADIgHAAQAAgGAGgDQADgBAHAAQAKAAADAFIABADIAAAGIAAAUIgFAAIAAgDQgCACgDABIgHABQgHAAgEgDgAj+ADQgBAAAAABQgBAAAAABQAAAAAAABQAAABAAABQAAABAAAAQAAABAAABQAAAAABABQAAAAABAAQABACAFAAQAFAAACgCQABAAAAAAQAAgBABAAQAAgBAAAAQAAgBABgBIABgGIgLAAQgFAAgBABgAlRAPQgCgCgBgEIgBgIIABgIQABgEACgBQAEgEAIAAQAKAAADAEQACACABADIABAIIgBAJQgBADgCACQgDAEgKAAQgIAAgEgEgAlLgJQgCABgBADIgBAGIABAHQABADACABQACABAEAAQAFAAADgBQAAAAAAgBQABAAAAgBQAAAAABgBQAAgBAAAAIAAgHIAAgGQAAgDgCgCIgIgBQgEAAgCACgAmgAQQgDgDAAgFQAAgHAFgCQADgBAGAAIALAAIgBgFQAAgBAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAIgGgBIgGABQgDABAAADIgGAAQAAgGAFgDQAEgBAGAAQALAAADAFIAAADIABAGIAAAUIgGAAIAAgDQgBACgDABIgIABQgGAAgEgDgAmbADQAAAAgBABQAAAAAAABQgBAAAAABQAAABAAABQAAABAAAAQAAABABABQAAAAAAABQABAAAAAAQACACAEAAQAFAAACgCQABAAAAAAQABgBAAAAQAAgBABAAQAAgBAAgBIABgGIgLAAQgFAAgBABgAIKASIAAgdIgMAAIAAgFIAeAAIAAAFIgMAAIAAAdgAHHASIAAgdIgNAAIAAgFIAfAAIAAAFIgMAAIAAAdgAGZASIgSAAIAAgiIAGAAIAAAPIAMAAIAFAAIAEABQACACAAAGQAAAGgCACIgDABIgEABIgCAAgAGNANIAJAAIAFAAIABgBQABAAAAAAQAAgBABAAQAAgBAAgBQAAAAAAgBIgBgEIgCgBIgFAAIgJAAgAFvASIAAgdIgMAAIAAgFIAeAAIAAAFIgMAAIAAAdgAFWASIAAgiIAGAAIAAAigAFGASIAAgPIgRAAIAAAPIgGAAIAAgiIAGAAIAAAPIARAAIAAgPIAGAAIAAAigAD5ASIAAgZIgSAZIgGAAIAAgiIAGAAIAAAZIARgZIAHAAIAAAigADJASIAAgdIgNAAIAAgFIAfAAIAAAFIgNAAIAAAdgACfASIAAgPIgDAAIgEABIgCAAIAAABIgDAEIgGAJIgHAAIAKgPQgGAAgBgDQgCgBAAgFQAAgGAFgDIAJgBIAQAAIAAAigACRgKIgCAAQAAABgBAAQAAAAAAABQAAAAAAABQgBAAAAABQAAABABABQAAABAAAAQAAABABAAQAAAAAAABIAGAAIAKAAIAAgKIgJAAIgFABgAB4ASIAAgiIAFAAIAAAigAAYASIAAgYIgLAYIgGAAIgJgYIAAAYIgGAAIAAgiIAIAAIAKAbIAMgbIAIAAIAAAigAilASIAAgPIgRAAIAAAPIgHAAIAAgiIAHAAIAAAPIARAAIAAgPIAGAAIAAAigAjNASIAAgiIAGAAIAAAigAkcASIgPAAIAAgiIAOAAIAHAAIAEABQAEACAAAGQAAAHgDAAIACADIABAFQABAFgDADQgDACgDAAIgGAAgAklANIAJAAIAGgBQABAAAAAAQAAgBABAAQAAgBAAgBQAAAAAAgBIgBgEIgDgBIgFAAIgIAAgAklgBIAJAAIAEAAIADgBIABgEQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAgBgBQgBgBgDAAIgLAAgAlrASIgQAAIAAgiIAPAAIAHAAIAEABQAEACAAAGQAAAHgEAAIADADIABAFQAAAFgCADQgDACgDAAIgGAAgAl0ANIAJAAIAGgBQAAAAABAAQAAgBAAAAQABgBAAgBQAAAAAAgBIgBgEIgDgBIgFAAIgIAAgAl0gBIAJAAIAEAAIADgBIABgEQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQgCgBgEAAIgKAAgAnbASIAAgdIgRAAIAAAdIgGAAIAAgiIAdAAIAAAigAoKgIIgIAKIgEgCIAIgLIgOgEIACgFIAOAEIAAgNIAEAAIAAANIAOgEIACAFIgNAEIAIALIgFACgAFWgXIgBgDIABgDIADgBIADABIAAADIAAADIgDABIgDgBgAB4gXIgBgDIABgDIADgBIACABIABADIgBADIgCABIgDgBgAjMgXIgBgDIABgDIADgBIACABIABADIgBADIgCABIgDgBg");
	this.shape_1.setTransform(-79.4,13.925);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol20, new cjs.Rectangle(-135.5,6.5,112,13.2), null);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_5
	this.instance = new lib.lg_37();
	this.instance.parent = this;
	this.instance.setTransform(118,55);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_4
	this.instance_1 = new lib.Symbol17();
	this.instance_1.parent = this;
	this.instance_1.setTransform(156.55,198.7,1,1,0,0,0,119.7,24.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// Layer_3
	this.instance_2 = new lib.Symbol16();
	this.instance_2.parent = this;
	this.instance_2.setTransform(168.4,197.75,1,1,0,0,0,102.3,11.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(1));

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AsgCEIAAkHIZCAAIAAEHg");
	this.shape.setTransform(168.5,208.525);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Layer_6
	this.instance_3 = new lib.Symbol18();
	this.instance_3.parent = this;
	this.instance_3.setTransform(167.65,262.5,1,1,0,0,0,53.7,12.6);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(1));

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("A6PV4MAAAgrvMA0fAAAMAAAArvg");
	this.shape_1.setTransform(168,140);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol15, new cjs.Rectangle(0,0,336,280), null);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Символ7();
	this.instance.parent = this;
	this.instance.setTransform(2,2.7,1,1,0,0,0,2,2.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-0.25},12,cjs.Ease.get(-1)).to({x:2},12,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-2.2,-1.3,7.7,9.9);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1 copy
	this.light = new lib.Symbol98();
	this.light.name = "light";
	this.light.parent = this;
	this.light.setTransform(-40.8,-60.85,0.1892,0.1432,0,18.9329,13.5085,44.3,30.2);
	this.light.alpha = 0.1992;
	this.light.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.light).wait(1));

	// Layer_1
	this.light_1 = new lib.Symbol98();
	this.light_1.name = "light_1";
	this.light_1.parent = this;
	this.light_1.setTransform(-87.95,-60.95,0.0644,0.1045,0,82.2627,-129.4614,50.5,32.7);
	this.light_1.alpha = 0.1992;
	this.light_1.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.light_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol8, new cjs.Rectangle(-97.4,-72.6,74.60000000000001,23.999999999999993), null);


(lib.Symbol40 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.Symbol20();
	this.instance.parent = this;
	this.instance.setTransform(36.25,-9.55,1,1,0,0,0,37.8,10.4);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol40, new cjs.Rectangle(-135,-9.2,108.1,6.3999999999999995), null);


(lib.main = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop()
		var _this=this
		var __this = this.parent
		var count = 0;
		
		var main_tl = new TimelineMax({repeat:-1})
		
		
			.to(this.cover, 0.5,{alpha:0, ease:Power0.easeOut})
			.addCallback(function(){ __this.disclaimerBtn.alpha = 1},'-=0.5')
			
			.staggerFrom([this.t11], 0.5,{y:"+=40", ease:Power2.easeOut},'0.0','-=0.2')
				.to(this.light, 0.1,{alpha:1}, '+=0.0')
			.to(this.light, 0.5,{alpha:0, ease:Power3.easeOut}, '+=0')
				.to(this.light, 0.1,{alpha:1}, '+=0.0')
			.to(this.light, 0.5,{alpha:0, ease:Power3.easeOut}, '+=0')
		
			.from(this.bg2, 0.6,{alpha:0, ease:Power0.easeInOut}, '+=1.5')
			.staggerTo([this.t11], 0.4,{y:"-=40", ease:Power2.easeIn},'0.0','-=0.4')
			.staggerFrom([this.t12], 0.5,{y:"+=40", ease:Power2.easeOut},'0.0','-=0.2')
		
				.from(this.bg3, 0.6,{alpha:0, ease:Power0.easeInOut}, '+=1.5')
			.staggerTo([this.t12], 0.4,{y:"-=40", ease:Power2.easeIn},'0.0','-=0.4')
			.staggerFrom([this.t13], 0.5,{y:"+=40", ease:Power2.easeOut},'0.0','-=0.2')
		
			
			.from(this.bg4, 0.6,{alpha:0, ease:Power0.easeInOut}, '+=1.5')
			.staggerTo([this.t13], 0.4,{y:"-=40", ease:Power2.easeIn},'0.0','-=0.4')
			.staggerFrom([this.t14], 0.5,{y:"+=40", ease:Power2.easeOut, onComplete: stopAnimation},'0.0','-=0.2')	
			
			.from(this.last, 0.5,{alpha:0, ease:Power0.easeOut}, '+=2.2')
			
				.addCallback(function(){__this.disclaimerBtn.alpha = 0},'-=0.5')
			
			.to(this.cover, 0.5,{alpha:1, ease:Power0.easeOut},'+=2')
		
			
				function stopAnimation() {
				if (count < 1) {
					count++
				} else {
					TweenMax.killAll(),
					_this.tt.stop()
				}
			}	
		
		/*	.to(this.cover, 0.5,{alpha:0, ease:Power0.easeOut})
		
			.staggerTo([this.t11], 0.5,{alpha:0, ease:Power0.easeOut},'0.0','+=1.5')
			.from(this.bg2, 0.6,{alpha:0, ease:Power0.easeInOut}, '-=0.1')
			.staggerFrom([this.t12], 0.6,{alpha:0, ease:Power0.easeOut},'0.0','-=0.2')
		
			.staggerTo([this.t12], 0.5,{alpha:0, ease:Power0.easeOut},'0.0','+=1.5')
			.from(this.bg3, 0.6,{alpha:0, ease:Power0.easeInOut}, '-=0.1')
			.staggerFrom([this.t13], 0.6,{alpha:0, ease:Power0.easeOut},'0.0','-=0.2')
			
			.staggerTo([this.t13], 0.5,{alpha:0, ease:Power0.easeOut},'0.0','+=1.5')
			.from(this.bg4, 0.6,{alpha:0,ease:Power0.easeInOut}, '-=0.1')
			.staggerFrom([this.t14], 0.6,{alpha:0, ease:Power0.easeOut},'0.0','-=0.2')	
			
			.from(this.bg5, 0.6,{alpha:0, ease:Power0.easeInOut}, '+=1.5')
			.staggerFrom([this.pic, this.t15], 0.6,{alpha:0, ease:Power0.easeOut},'0.4','-=0.2')
		
			.from(this.bg6, 0.6,{alpha:0, ease:Power0.easeInOut}, '+=1.5')
			.staggerFrom([this.logo2, this.t16, this.t17,this.btn2 ], 0.6,{alpha:0, ease:Power0.easeOut},'0.0','-=0.2')
			
			.addCallPower2(function(){_this.btn2.tt.stop()},'+=1.2')
			
			.to(this.cover, 0.5,{alpha:0, ease:Power0.easeOut})
			.staggerFrom([this.t11, this.t12], 1,{alpha:0, ease:Power0.easeOut},'0.0','-=0.3')
			
			
			.staggerTo([this.t12], 0.5,{alpha:0, ease:Power0.easeOut},'0.0','+=2.5')
			.from(this.bg2, 1,{alpha:0, ease:Power0.easeOut}, '-=0.1')
			.staggerFrom([this.t22], 1,{alpha:0, ease:Power0.easeOut},'0.0','-=0.4')
			.from(this.btn, 0.5,{alpha:0, y:"+=10", ease:Power2.easeOut.config(1)},'-=0.2')
			
			.staggerTo([this.t22], 0.5,{alpha:0, ease:Power0.easeOut},'0.0','+=2.5')
			.from(this.bg3, 1,{alpha:0, ease:Power0.easeOut}, '-=0.1')
			.staggerFrom([this.t32], 1,{alpha:0, ease:Power0.easeOut},'0.0','-=0.4')
			
			.staggerFrom([this.disclaimer], 1,{alpha:0, ease:Power0.easeOut},'0.0','+=2.4')
		
			.to(this.cover, 0.5,{alpha:1, ease:Power0.easeOut},'+=2.4')
		
			
		var btn_tl = new TimelineMax()
		.to(this.btn.tt, 0.3, {x:"+=2", repeat:-1, yoyo:true, ease:Power1.easeInOut})
		
			
		var frequency = 40
		stage.enableMouseOver(frequency);
		
		canvas.addEventListener("mouseover", mouseOverBanner.bind(this));
		canvas.addEventListener("mouseout", mouseOutBanner.bind(this));
		
		function mouseOverBanner() {
			TweenMax.to(this.btn, 0.4,{scaleX:1.1, scaleY:1.1, ease:Power2.easeOut.config(2.2)})
		}
		function mouseOutBanner() {
			TweenMax.to(this.btn, 0.4,{scaleX:1.0, scaleY:1.0, ease:Power2.easeOut.config(3)})
		}
			*/
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// cover
	this.cover = new lib.Symbol1();
	this.cover.name = "cover";
	this.cover.parent = this;
	this.cover.setTransform(168,140,1.1202,1.12,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.cover).wait(1));

	// disclaimer
	this.last = new lib.Symbol15();
	this.last.name = "last";
	this.last.parent = this;
	this.last.setTransform(150,300,1,1,0,0,0,150,300);

	this.timeline.addTween(cjs.Tween.get(this.last).wait(1));

	// logo
	this.instance = new lib.lg336();
	this.instance.parent = this;
	this.instance.setTransform(245,13);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	// Layer_14 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AyxGaQgdAAgBgjIAAjvQABgiAdAAMAotAAAQAeAAAAAiIAADvQAAAjgeAAg");
	mask.setTransform(143.4,40.975);

	// Layer_13
	this.t14 = new lib.Symbol12();
	this.t14.name = "t14";
	this.t14.parent = this;
	this.t14.setTransform(88.9,67.2,0.9261,0.9261,0,0,0,72.9,18.2);

	var maskedShapeInstanceList = [this.t14];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.t14).wait(1));

	// Layer_12 copy
	this.t13 = new lib.Symbol22();
	this.t13.name = "t13";
	this.t13.parent = this;
	this.t13.setTransform(91.4,67.55,1,1,0,0,0,70,17.2);

	var maskedShapeInstanceList = [this.t13];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.t13).wait(1));

	// Layer_12
	this.t12 = new lib.Symbol11();
	this.t12.name = "t12";
	this.t12.parent = this;
	this.t12.setTransform(90.85,67.2,0.9261,0.9261,0,0,0,75,18.2);

	var maskedShapeInstanceList = [this.t12];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.t12).wait(1));

	// Layer_5
	this.t11 = new lib.Symbol7();
	this.t11.name = "t11";
	this.t11.parent = this;
	this.t11.setTransform(81.2,74.85,0.9261,0.9261,0,0,0,66.6,9.5);

	var maskedShapeInstanceList = [this.t11];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.t11).wait(1));

	// arrow
	this.tt = new lib.Symbol23();
	this.tt.name = "tt";
	this.tt.parent = this;
	this.tt.setTransform(13.95,57.6,0.931,0.7846);

	this.timeline.addTween(cjs.Tween.get(this.tt).wait(1));

	// t1
	this.instance_1 = new lib.Symbol6();
	this.instance_1.parent = this;
	this.instance_1.setTransform(85.1,27,1.1097,1.1097,0,0,0,68,18.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(1));

	// bg4.jpg
	this.bg4 = new lib.Symbol5();
	this.bg4.name = "bg4";
	this.bg4.parent = this;
	this.bg4.setTransform(150,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.bg4).wait(1));

	// bg3
	this.bg3 = new lib.Symbol21();
	this.bg3.name = "bg3";
	this.bg3.parent = this;
	this.bg3.setTransform(150,300,1,1,0,0,0,150,300);

	this.timeline.addTween(cjs.Tween.get(this.bg3).wait(1));

	// bg2.jpg
	this.bg2 = new lib.Symbol3();
	this.bg2.name = "bg2";
	this.bg2.parent = this;
	this.bg2.setTransform(150,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.bg2).wait(1));

	// light
	this.light = new lib.Symbol8();
	this.light.name = "light";
	this.light.parent = this;
	this.light.setTransform(155.95,327,1.9012,1.9012,0,0,180,-26.1,16.1);
	this.light.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.light).wait(1));

	// bg1.jpg
	this.bg1 = new lib.Symbol2();
	this.bg1.name = "bg1";
	this.bg1.parent = this;
	this.bg1.setTransform(150,125,1,1,0,0,0,150,125);

	this.timeline.addTween(cjs.Tween.get(this.bg1).wait(1));

}).prototype = getMCSymbolPrototype(lib.main, new cjs.Rectangle(0,0,336,280), null);


(lib.Symbol41 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{st:0});

	// timeline functions:
	this.frame_0 = function() {
		this.gotoAndPlay(1)
	}
	this.frame_49 = function() {
		this.stop()
	}
	this.frame_68 = function() {
		this.stop()
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(49).call(this.frame_49).wait(19).call(this.frame_68).wait(1));

	// Layer 1
	this.instance = new lib.Symbol40();
	this.instance.parent = this;
	this.instance.setTransform(45.1,11.8,1,1,0,0,0,45.1,11.8);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:0},0).wait(23).to({alpha:1},25).to({alpha:0},19).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-135,-9.2,108.1,6.3999999999999995);


(lib.disclaimerBtn = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.dc = new lib.Symbol41();
	this.dc.name = "dc";
	this.dc.parent = this;
	this.dc.setTransform(44.95,6.85,1,1,0,0,0,45.1,11.8);

	this.instance = new lib.Symbol41();
	this.instance.parent = this;
	this.instance.setTransform(44.95,6.85,1,1,0,0,0,45.1,11.8);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AqCArIAAhVIUFAAIAABVg");
	this.shape.setTransform(-79.15,-11.825);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.dc}]}).to({state:[{t:this.shape},{t:this.instance}]},3).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-143.4,-16.1,128.6,8.600000000000001);


// stage content:
(lib.LR_DS_apr20_336x280 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		//////////////////////////////////////////////////////////////////
		/////////////////created by ADBANNER.com.ua 2019//////////////////
		//////////////////////////////////////////////////////////////////
		//////////////////////////////////////////////////////////////////
		this.stop()
		var _this = this
		var Tween
		this.disclaimer.alpha = 0
		
		
		///////////////////////////////////////////////////////////
		this.disclaimerBtn.addEventListener('mouseover', disclaimerBtnOver)
		
		function disclaimerBtnOver() {
			_this.disclaimer.alpha = 1
		
		}
		
		this.disclaimerBtn.addEventListener('mouseout', disclaimerBtnOut)
		
		function disclaimerBtnOut() {
			_this.disclaimer.alpha = 0
		
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(25));

	// Layer_1
	this.disclaimer = new lib.Symbol12_1();
	this.disclaimer.name = "disclaimer";
	this.disclaimer.parent = this;
	this.disclaimer.setTransform(150,300,1,1,0,0,0,150,300);

	this.timeline.addTween(cjs.Tween.get(this.disclaimer).wait(25));

	// disclaimerBtn
	this.disclaimerBtn = new lib.disclaimerBtn();
	this.disclaimerBtn.name = "disclaimerBtn";
	this.disclaimerBtn.parent = this;
	this.disclaimerBtn.setTransform(525.45,305.55,1.6658,1.6658,0,0,0,91.8,9.4);
	new cjs.ButtonHelper(this.disclaimerBtn, 0, 1, 2, false, new lib.disclaimerBtn(), 3);

	this.timeline.addTween(cjs.Tween.get(this.disclaimerBtn).wait(25));

	// main
	this.instance = new lib.main();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(25));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(152.3,128.2,203.8,170.3);
// library properties:
lib.properties = {
	id: '4E6C08E546539F4389CF57D8068DAF92',
	width: 336,
	height: 280,
	fps: 60,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"./b11.jpg", id:"b11"},
		{src:"./b12.jpg", id:"b12"},
		{src:"./b13.jpg", id:"b13"},
		{src:"./b14.jpg", id:"b14"},
		{src:"./Bitmap1.png", id:"Bitmap1"},
		{src:"./Bitmap2.png", id:"Bitmap2"},
		{src:"./Bitmap3.png", id:"Bitmap3"},
		{src:"./lg336.png", id:"lg336"},
		{src:"./lg_37.png", id:"lg_37"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['4E6C08E546539F4389CF57D8068DAF92'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;