(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib._336x280_pic = function() {
	this.initialize(img._336x280_pic);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,280);


(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,336,61);


(lib.icon = function() {
	this.initialize(img.icon);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.machine = function() {
	this.initialize(img.machine);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,304,172);


(lib.machine_icon = function() {
	this.initialize(img.machine_icon);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,111,138);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween20copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ADhCLIAAkWIAOAAIAAEWgANSBbQgOgHgNgLQgLgMgIgPQgHgSAAgVQAAgTAHgRQAIgRALgLQAMgLAPgGQAPgGAQAAQASAAAOAGQAOAGAKAMIAAgUIAnAAIAACpIgnAAIAAgXQgKANgOAGQgPAIgRgBQgPAAgQgFgANjgoQgJAEgIAHQgGAHgEAJQgEALAAAJQAAALAEAKQAEAKAGAHQAIAHAJAEQAJAFALgBQALABAJgFQAKgEAHgHQAGgIAEgJQAFgKAAgLQAAgKgFgJQgEgKgGgHQgHgHgKgEQgJgFgLAAQgLAAgJAFgAKXBZQgRgGgLgNQgMgLgHgRQgGgQgBgSQABgSAGgQQAHgQAMgMQAMgMAQgIQAQgGATAAQATAAAQAGQARAHALAMQALAMAHAPQAHARAAARIAAAQIiLAAQAEARANALQAPALAUAAQARAAAMgIQANgHAFgOIAhASQgLAUgUAOQgUANgdgBQgTABgRgIgALpgLQgEgQgMgKQgNgIgSgBQgSABgMAJQgNAKgGAPIBgAAIAAAAgAieBWQgTgLgKgUIAlgSQAFAMALAHQALAGANAAQAPAAAIgGQAGgGAAgJQAAgEgDgDIgJgFIgxgNQgLgCgJgHQgIgFgFgIQgFgIAAgOQAAgLAFgJQAEgJAJgIQAJgGAMgFQAMgFAQAAQAaAAARALQAQAIALAQIghASQgGgJgJgFQgKgGgMAAQgOABgHAFQgGAGAAAHQAAAIAKADQAKAFASADIAVAGQALADAJAFQAIAFAGAKQAFAIABANQAAAKgFAJQgDAKgJAIQgJAJgNAFQgNAGgSgBQgcABgTgLgAlCBbQgQgHgLgLQgNgMgHgPQgHgSAAgVQAAgTAHgRQAHgRAMgLQAMgLAPgGQAPgGAQAAQARAAAOAGQAPAGAJAMIAAgUIAnAAIAACpIgnAAIAAgXQgJANgPAGQgPAIgQgBQgPAAgPgFgAkzgoQgIAEgHAHQgIAHgDAJQgEALAAAJQAAALAEAKQADAKAIAHQAHAHAIAEQAKAFALgBQALABAKgFQAJgEAHgHQAHgIAEgJQADgKAAgLQAAgKgDgJQgEgKgHgHQgHgHgJgEQgKgFgLAAQgLAAgKAFgAsvBbQgPgHgMgLQgMgMgHgPQgIgSABgVQgBgTAIgRQAGgRANgLQALgLAQgGQAPgGAPAAQARAAAPAGQAOAGAJALIAAhBIAoAAIAADXIgoAAIAAgXQgIANgPAGQgPAIgRgBQgPAAgPgFgAsfgoQgJAEgHAHQgHAHgEAJQgDALgBAJQABALADAKQAEAKAHAHQAHAHAJAEQAKAFALgBQALABAJgFQAJgEAHgHQAGgIAFgJQAEgKAAgLQAAgKgEgJQgFgKgGgHQgHgHgJgEQgJgFgLAAQgLAAgKAFgAvzBbQgOgHgMgLQgMgMgIgPQgHgSAAgVQAAgTAHgRQAIgRALgLQAMgLAPgGQAPgGARAAQAQAAAOAGQAOAGAKALIAAhBIAoAAIAADXIgnAAIAAgXQgKANgPAGQgPAIgQgBQgPAAgQgFgAvigoQgJAEgIAHQgGAHgEAJQgEALAAAJQAAALAEAKQAEAKAGAHQAIAHAJAEQAJAFALgBQALABAKgFQAJgEAHgHQAGgIAFgJQADgKABgLQgBgKgDgJQgFgKgGgHQgHgHgJgEQgKgFgLAAQgLAAgJAFgAFnBVQgUgLgNgQIgBAAIABgBIAjgcQAIAOAMAHQAMAHAPABQAHAAAGgCQAHgDAEgEQADgDACgGQADgFAAgGQAAgHgEgEQgEgEgFgEIg1gSQgKgEgJgHQgJgHgGgKQgEgKAAgPQAAgNAEgLQAGgLAJgIQAKgIAMgFQANgFAQAAQANAAAKADQAKACAJAFQAIADAHAGIAOAMIggAZQgOgVgZABQgPgBgHAIQgIAHAAAJQAAAHAEAFQADAEAGAEIA1ATQAKAEAKAHQAIAIAFAJQAHALgBAPQAAAMgFAMQgFAMgJAJQgJAJgOAGQgNAFgSAAQgdABgUgLgATKBdIAAhiQAAgUgJgKQgKgLgSAAQgQAAgLALQgLALAAAWIAABfIgnAAIAAhjQAAgTgJgLQgKgKgSAAQgQAAgLAMQgLALAAAWIAABeIgnAAIAAipIAnAAIAAATQAIgLANgGQAMgGAPAAQAVAAAOAHQANAJAHAOQAJgOAPgIQAOgIASAAQAjAAARATQARATAAAhIAABmgAJPBdQgUgBgNgDQgOgDgHgJQgIgIgDgNQgDgOAAgUIAAg/IgeAAIAAgjIAeAAIAAgbIAngbIAAA2IAiAAIAAAjIgiAAIABBRQABAGAEADQADAEAIACIARABIAAAlgABcBdIAAhgQAAgUgKgLQgJgMgUAAQgIAAgHADQgHADgGAGQgFAGgEAIQgCAJAAALIAABdIgnAAIAAjXIAnAAIAABCQAIgMANgGQANgGARAAQAfAAASATQASAUAAAiIAABkgAnlBdIgtiVIgsCVIgpAAIg8jUIApAAIAoCUIAsiUIAoAAIAsCUIAoiUIAoAAIg8DUgAxbBdIgNgmIhSAAIgNAmIgpAAIBLjUIAoAAIBLDUgAx0ARIgchQIgdBQIA5AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-126.5,-13.9,253.1,27.9);


(lib.Tween20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ADhCLIAAkWIAPAAIAAEWgANTBaQgPgGgMgLQgMgMgIgQQgHgRAAgUQAAgVAHgQQAIgRALgKQAMgMAPgGQAPgGAQAAQARAAAPAGQAOAHAJALIAAgVIAoAAIAACpIgoAAIAAgVQgJALgOAIQgQAGgQABQgQgBgOgGgANjgoQgKAEgGAHQgIAHgDAJQgEAKAAAKQAAALAEAKQADAKAIAHQAGAHAKAEQAKAFALAAQAKAAAKgFQAJgEAHgHQAHgIADgJQAEgKAAgLQAAgKgEgJQgDgJgHgIQgHgHgJgEQgKgEgKAAQgLAAgKAEgAKXBaQgQgIgMgLQgMgMgHgQQgGgRAAgSQAAgSAGgQQAHgQAMgMQAMgMAQgHQAQgHATAAQATAAAQAHQAQAGAMAMQAMAMAGAQQAHAPAAATIAAAOIiLAAQAEATANALQAOAKAWABQAQgBAMgHQAMgJAGgNIAhASQgLAVgUAMQgVAOgbAAQgUgBgRgGgALpgKQgEgSgMgIQgMgKgTABQgSgBgNALQgNAIgFARIBgAAIAAAAgAieBVQgTgKgKgUIAkgSQAHAMAKAGQAKAHAPAAQAOAAAHgGQAIgGgBgIQAAgGgCgCIgJgGIgygLQgKgDgKgGQgHgGgFgIQgGgJAAgNQAAgLAFgJQAEgJAJgHQAJgIAMgEQANgEAPAAQAZgBASALQAQAJALAQIghARQgGgJgJgGQgKgEgMAAQgOgBgHAGQgGAGAAAHQAAAIAKAEQAJADAUAEIAUAGQALADAJAFQAIAFAGAKQAGAIgBANQAAAKgEAKQgEAJgIAJQgIAHgOAGQgNAGgSAAQgcAAgTgMgAlDBaQgPgGgMgLQgMgMgHgQQgHgRAAgUQAAgVAHgQQAHgRAMgKQAMgMAPgGQAPgGARAAQAQAAAOAGQAPAHAKALIAAgVIAmAAIAACpIgmAAIAAgVQgKALgPAIQgOAGgRABQgQgBgPgGgAkzgoQgIAEgIAHQgGAHgEAJQgEAKAAAKQAAALAEAKQAEAKAGAHQAIAHAIAEQALAFAKAAQALAAAKgFQAJgEAHgHQAGgIAFgJQADgKAAgLQAAgKgDgJQgFgJgGgIQgHgHgJgEQgKgEgLAAQgKAAgLAEgAsvBaQgPgGgMgLQgMgMgIgQQgGgRAAgUQAAgVAGgQQAIgRALgKQAMgMAPgGQAQgGAQAAQAQAAAPAGQAOAHAJALIAAhCIAoAAIAADWIgoAAIAAgVQgJALgOAIQgPAGgRABQgPgBgPgGgAsfgoQgJAEgHAHQgHAHgEAJQgDAKAAAKQAAALADAKQAEAKAHAHQAHAHAJAEQAJAFAMAAQAKAAAKgFQAJgEAHgHQAHgIAEgJQAEgKgBgLQABgKgEgJQgEgJgHgIQgHgHgJgEQgKgEgKAAQgMAAgJAEgAvyBaQgPgGgMgLQgMgMgHgQQgIgRABgUQgBgVAIgQQAGgRAMgKQAMgMAPgGQAPgGAQAAQARAAAPAGQAOAHAJALIAAhCIAoAAIAADWIgoAAIAAgVQgIALgPAIQgPAGgRABQgPgBgPgGgAvigoQgKAEgGAHQgIAHgDAJQgEAKAAAKQAAALAEAKQADAKAIAHQAGAHAKAEQAKAFALAAQAKAAAKgFQAJgEAHgHQAGgIAFgJQAEgKAAgLQAAgKgEgJQgFgJgGgIQgHgHgJgEQgKgEgKAAQgLAAgKAEgAFnBUQgUgKgOgQIAAgBIAAAAIAkgcQAIAOAMAHQAMAIAOgBQAJAAAFgCQAGgCAFgEQAEgEACgFQACgGAAgFQAAgGgEgFQgDgFgGgDIg1gSQgLgEgIgHQgJgGgGgKQgEgLgBgPQABgNAEgLQAGgKAJgJQAKgIAMgFQAOgFAPAAQANAAAKADQALACAIAEQAIAEAIAGIANANIggAYQgOgVgZAAQgOAAgIAIQgIAHAAAKQAAAGAEAEQADAFAGADIA0ATQALAFAJAHQAJAIAFAJQAGALABAOQAAANgGAMQgFAMgJAJQgJAJgOAGQgOAGgRAAQgdAAgUgMgATKBcIAAhiQAAgSgKgLQgJgLgTAAQgPAAgLALQgLALAAAXIAABdIgnAAIAAhjQgBgSgIgKQgKgLgRAAQgSAAgKAMQgLALAAAXIAABcIgnAAIAAipIAmAAIAAAVQAJgLANgHQAMgGAQAAQATAAAPAIQANAHAIAOQAIgNAPgHQAPgJARAAQAjAAASATQAQATABAiIAABkgAJPBcQgTABgOgEQgNgEgIgHQgIgJgDgOQgEgNAAgVIAAg+IgdAAIAAgkIAdAAIAAgaIAogbIAAA1IAiAAIAAAkIgiAAIABBQQABAIADACQAFAFAGABIASAAIAAAlgABbBcIAAheQAAgVgJgLQgJgMgUAAQgJAAgHADQgHADgFAGQgFAGgEAJQgCAIAAALIAABcIgnAAIAAjWIAnAAIAABCQAIgLANgHQANgGAQAAQAgAAATATQARATAAAjIAABjgAnlBcIgtiUIgtCUIgnAAIg9jSIApAAIAoCTIAsiTIAoAAIAsCSIAoiSIAoAAIg9DSgAxbBcIgNglIhSAAIgNAlIgpAAIBLjSIAoAAIBMDSgAx1ASIgchQIgcBQIA4AAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-126.5,-13.9,253.1,27.9);


(lib.Symbol24 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhYBSIAWg5IgthoIAbAAIAgBLIAdhLIAaAAIhCChgAlJBSIAAihIAZAAIAAAPQAGgIAJgEQAKgFALAAQAKAAAKAEQAKAEAIAHQAHAIAFAKQAFAMAAANQgBANgFAKQgDAJgIAJQgIAIgKAEQgUAHgVgHQgJgFgGgHIAABAgAkdg3QgGACgFAFIgGALQgDAFAAAJQAAAHADAGIAGAKQAFAFAGACQAGADAHAAQAHAAAGgDQANgGAFgLQACgHAAgGQAAgIgCgGQgDgHgEgEQgFgFgGgCQgGgDgHAAQgHAAgGADgAmxBSIAYg5IgthoIAbAAIAeBLIAehLIAbAAIhDChgAFrAdQgJgEgJgJQgNgNgDgQQgEgRAHgQQAEgJAJgKQAGgGAMgFQAKgFAMAAQAJAAAJADQAHACAIAEQAHAFAFAHQAEAEAEAJIgWAKQgFgKgIgEQgHgGgLAAQgGAAgGACQgGAEgFAEQgEAEgDAGQgCAGAAAIQAAAHACAFQADAIAEADQAFAFAGABQAGADAHAAQAKABAIgGQAIgGAEgJIAWAKQgDAJgFAFQgEAFgIAFQgHAFgIADQgIACgKAAQgMABgKgFgAAjAdQgKgEgJgJQgHgIgFgJQgHgXAHgXQAGgLAHgHQAIgHAKgEQALgFAMAAQASAAAOAIQAOAJAHAOIgXALQgDgIgIgGQgJgFgKAAQgLAAgJAHQgJAGgEALIAtAAIAAAVIgtAAQADALAJAGQAKAHALgBQALABAIgHQAIgEAEgJIAXALQgIAOgNAIQgJAFgGACQgJADgJgBQgLABgMgFgAIDAfIAAghIgaAAIgQAhIgcAAIAUgnQgIgFgEgJQgEgIAAgKQAAgJADgHQACgHAHgFQAGgGAHgCQAJgDAJAAIAxAAIAABugAHgg0QgFAEAAAIIABAGQABADACACQADADADABQAEABAEABIAWAAIAAgiIgWAAIgCAAQgGAAgFAFgADhAfIAAhuIAZAAIAAAhIAXAAQAJAAAKAEQAHABAGAHQAFAEAEAIQAEAHAAAIQgBAPgMAMQgGAFgHADQgJADgJAAgAD6AIIAWAAQAIABAGgFIADgCQADgEAAgHQAAgGgGgEQgGgFgIABIgWAAgACZAfIAAhWIgjAAIAAgYIBfAAIAAAYIgjAAIAABWgAixAfIAAhWIgiAAIAAgYIBeAAIAAAYIgiAAIAABWgAocAfIAAhuIBNAAIAAAYIgzAAIAABWg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-54,-8.2,108.1,16.4);


(lib.Symbol23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ai0BKQgLgFgIgIQgMgNgDgRQgEgRAHgPQAEgKAIgJQAHgHAMgFQAKgFAMAAQAJAAAJADQAIADAHAEQAHAFAFAGIAIAOIgXAIQgEgIgIgFQgIgFgKgBQgHAAgGADQgFACgFAFQgEADgDAHQgCAGAAAIQAAAHACAFQADAHAEAEQAEAEAGADQAIADAGAAQAKAAAIgGQAIgFADgKIAXAKQgDAIgFAHIgMAKQgHAFgIADQgKACgIAAQgMAAgKgEgAB6BMIATgoQgIgFgEgJQgEgJAAgJQAAgHADgIQACgHAGgFQAGgGAIgCQAKgDAIAAIAwAAIAABuIgZAAIAAgiIgbAAIgPAiIAAAAgACbgHQgEAEAAAGIABAHQAAACADADIAGAEQAEABAEABIAWAAIAAghIgWAAIgBAAQgHAAgGAFgAhdBMIAAhuIAaAAIAABugAArBMIAAhJIgjAoIgignIAABIIgZAAIAAhuIAYAAIAjAqIAmgqIAWAAIAABugABTgXIAGgmIAXAAIgNAmgAhRgtQgHAAgEgEQgEgEAAgIQAAgHAEgFQAFgEAHAAQAHAAAFAEQAFAGgBAGQABAHgGAFQgFAFgFAAIgCgBg");
	this.shape.setTransform(-0.0333,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-21.6,-7.8,43.2,15.6);


(lib.Symbol22 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjIBnIAYg5IguhoIAbAAIAfBJIAdhJIAbAAIhCChgAD8AxQgKgDgIgJQgIgIgFgKQgJgWAJgWQAFgLAIgIQAHgHALgFQALgFALABQAIAAAKACQAHACAIAFQAHAFAFAGQAGAIACAFIgXALQgDgJgIgGQgJgGgJAAQgHAAgGADQgGADgFAEQgFAGgCAFQgCAHAAAGQAAAGACAGQADAGAEAFQAFAFAGACQAGADAHAAQAKAAAIgGQAIgGAEgJIAXAKQgDAIgGAGQgEAFgHAGIgQAHQgJADgJAAQgMAAgKgFgAhLAxQgLgEgHgIQgJgJgDgJQgKgWAKgXQAFgLAHgHQAIgJAKgDQAMgFALABQASgBAOAJQANAJAHANIgVALQgFgIgHgFQgIgGgLAAQgLAAgKAHQgJAIgCAKIAtAAIAAATIguAAQAEAMAIAGQAKAHAMAAQAKAAAJgGQAHgGAEgIIAVALQgGANgNAKIgPAGQgKADgHAAQgMAAgMgFgAGUAzIAAghIgbAAIgPAhIgbAAIATgnQgIgFgEgIQgEgJAAgKQAAgIADgIQADgGAFgGQAHgFAHgDQAJgCAJAAIAwAAIAABtgAFxgfQgGAEABAHIABAHQABADACACQADADADABIAJABIAVAAIAAghIgVAAIgDAAQgGAAgFAFgAByAzIAAhtIAaAAIAAAhIAWAAQAKAAAIADQAHACAHAGQAGAFADAHQADAHAAAIQAAARgMAKQgGAGgHADQgJACgJAAgACMAdIAVAAQAHABAHgGIACgBQAEgFAAgHQgBgGgFgEQgHgFgHABIgVAAgAAqAzIAAhVIgjAAIAAgYIBfAAIAAAYIgiAAIAABVgAjrAzIgfhLIgeBLIgaAAIAshtIAYAAIAtBtgAlmAzIgngrIgJAAIAAArIgaAAIAAhtIAaAAIAAArIAIAAIAmgrIAfAAIgwA2IAyA3gAnaAzIAAhtIAaAAIAABtgAoEAzIAAhWIguAAIAABWIgaAAIAAhtIBhAAIAABtgAHugEIAAgXIBfAAIAAAXgAnOhEQgHAAgEgGQgEgFAAgGQAAgIAEgEQAFgEAHgBQAHABAFAEQAEAEAAAIQAAAHgFAFQgFAFgGAAIgBAAg");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-58.8,-10.2,117.69999999999999,20.5);


(lib.Symbol21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AjJBOQgNAAgLgFQgWgIgJgWQgEgLAAgLQAAgNAEgJQAFgLAIgIQAHgHALgFQALgEAMAAQALgBALAFQALAEAHAIQAIAHAEALQAFAKAAAMIAAAJIhbAAQADAMAJAHQAKAIAMgBQALAAAIgFQAIgFAEgJIAVAMQgGANgOAJQgNAIgPAAIgDAAgAirAIQgDgKgIgGQgJgGgLAAQgLAAgJAGQgJAGgDAKIA/AAIAAAAgAELBKQgKgEgHgHQgHgHgGgLQgFgMAAgNQAAgNAFgKQAEgKAIgIQAIgIAKgEQAJgDALAAQALgBAKAFQAIADAHAIIAAgNIAaAAIAABuIgaAAIAAgPQgHAJgJADIAAABQgJAEgLAAQgMAAgIgEgAEWgLQgGADgFAFQgFAEgCAFQgCAGAAAIQAAAIACAFQAFANANAGQANAFANgFQAGgCAFgGQAEgEADgHQACgGAAgHQAAgHgCgGQgDgHgEgDQgFgFgGgDQgGgCgHAAQgHAAgGACgADQBMIgmgsIgKAAIAAAsIgZAAIAAhuIAZAAIAAAqIAIAAIAngqIAeAAIgwA1IAyA5gABcBMIAAhuIAaAAIAABugAAyBMIAAgtIgwAAIAAAtIgZAAIAAhuIAZAAIAAAqIAwAAIAAgqIAaAAIAABugAg+BMIgcglIgaAlIgfAAIAqg5Igpg1IAgAAIAZAiIAZgiIAeAAIgoA1IArA5gAk3BMIAAhxIglAAIAAgZIBkAAIAAAZIglAAIAABxgABogtQgGAAgFgFQgFgFABgGQAAgHAEgFQAGgEAGAAQAHAAAFAEQAEAFAAAHQAAAHgFAFQgFAEgFAAIgCAAg");
	this.shape.setTransform(-0.025,0.005);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.9,-7.8,69.8,15.6);


(lib.Symbol19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.machine_icon();
	this.instance.parent = this;
	this.instance.setTransform(-55.5,-69);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-55.5,-69,111,138);


(lib.Symbol18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("A6PV4MAAAgrvMA0fAAAMAAAArvg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,-140,336,280);


(lib.Symbol17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Ag9A5IAAhvIAKAAIAAAKQAEgGAGgDQAGgDAIAAQAOAAAIALQAIAPgBARIgBAAQACAPgJAPQgIAMgPgBQgNAAgIgJIAAAmgAgpgrQgFADgEAEIAAAsQAEAFAGACQAGADAFAAQAKABAFgJQAGgKgBgNQABgOgGgKQgGgJgKABIgCAAQgEAAgFACgABVARQgKgNABgSQgBgRAJgOIADgDQAKgJANABQANAAAJAKQAJANgBAQIAAAGIg1AAQgBALAIAKQAHAIALgBQAMAAAIgGIAEAJQgFAEgGACQgGACgIAAIgCAAQgPAAgJgLgABdgoQgFAJgBALIAqAAQABgLgGgIQgHgIgJABIgCAAQgIAAgFAGgAiFAQQgLgNACgRQgCgQAKgPIADgDQAKgJANABQANAAAIAKQAKAMgBARIgBAGIg0AAQgBALAHAKQAIAIALgBQALAAAJgGIAEAJQgFADgGADIgOACIgDAAQgOAAgJgMgAhZgUQAAgLgGgIQgGgIgJABQgKAAgFAGQgGAKAAAKIAqAAIAAAAgAkUAbQgKABgJgHQgHgIABgKQgBgNAMgHQASgIATABIAAgGQABgHgGgFQgHgEgHAAQgKAAgJAFIgDgKQALgFAMAAQAMAAAJAGQAIAIgBAMIAAA4IgJAAIAAgKQgJALgMAAIgDAAgAkHAPQAGgDAEgEIAAgXQgPgBgOAGQgJAEAAAJQAAAGAFAFQAGAEAGgBQAFABAGgDgAjkASQAHgDAEgFQADgEACgGIACgOIADgoIAuAAIAABQIgLAAIAAhHIgZAAIgDAgIgCASQgCAGgFAGQgGAGgIAEgAEkAaIAAg+IgpA+IgKAAIAAhQIAKAAIAAA+IApg+IALAAIAABQgADPAaIAAgjIgnAAIAAAjIgKAAIAAhQIAKAAIAAAjIAnAAIAAgjIAKAAIAABQgAAUAaIAAhQIAvAAIAAAJIgkAAIAABHg");
	this.shape.setTransform(-0.0037,0.0237);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.2,-5.7,60.5,11.5);


(lib.Symbol16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAPAxQALgEAGgGQAHgFAEgIIgdhRIAMAAIAWBDIAWhDIAMAAIgdBRQgDALgJAIQgKAKgMADgAh/AxQAKgFAHgFQAHgFAEgIIgdhRIAMAAIAWBDIAWhDIALAAIgcBRQgDALgJAIQgKAKgMADgAgsAQQgLgPACgQQgBgLAFgLQADgJAJgFQAIgGAKAAQAGAAAGACIAKAFIgDAIQgKgFgJAAQgKgBgHAJQgHALABAMQgBAOAHAKQAIAKALgBQAJAAAIgFIAEAIQgEAEgGABQgGACgGAAIAAAAIgDAAQgOAAgJgLgACuAUQgHgHABgKQgBgNAMgIQASgHATAAIAAgFQABgHgGgFQgGgFgIABQgJAAgKAEIgDgJQALgGAMAAQALAAAKAHQAJAIgBALIAAA4IgKAAIAAgKQgJANgPgBIgDAAQgJAAgHgHgAC8gLQgKADAAAKQAAAHAFAEQAGAEAGAAQAHAAAEgDQAGgCAEgFIAAgXQgPAAgNAFgAjnAUQgIgHABgKQgBgNANgIQASgHASAAIAAgFQABgHgGgFQgGgFgIABQgJAAgJAEIgDgJQALgGAMAAQALgBAJAIQAJAHgBAMIAAA4IgKAAIAAgKQgIANgQgBIgCAAQgJAAgHgHgAjagLQgJAEAAAJQAAAHAEAEQAGAEAGAAQAHAAAFgDQAGgCADgFIAAgXQgPAAgNAFgAD9AQQgLgPACgQQAAgMAEgKQAEgJAIgGQAHgFALAAIAMACIALAFIgEAIQgKgFgJAAQgJAAgHAHQgHAJAAALIAgAAIAAAJIggAAQAAALAHAJQAIAJAKgBQAJAAAJgGIAEAJQgEAEgHABQgGACgGAAIgDAAQgOAAgJgLgACCAZIghAAIAAhQIAdAAQAKgBAIAHQAHAHgBAJQAAAGgDAEQgCAFgGABIABAAQAGACAFAFQAEAGAAAGQABAKgIAHQgIAGgJAAIgBAAgABrAQIAXAAQAGAAAEgEQAEgFgBgFQABgEgEgFQgEgEgHAAIgWAAgABrgUIAUAAQAGAAAEgDQAEgEgBgFQABgGgEgEQgGgEgFABIgTAAgAkXAZIAAhGIgWAAIAAgKIA3AAIAAAKIgWAAIAABGg");
	this.shape.setTransform(0.025,-0.0059);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.1,-5.8,60.3,11.6);


(lib.Symbol14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ABlBJIAAhvIAKAAIAAAKQADgFAHgEQAGgDAHAAQAPAAAHALQAJAPgBAQQABAQgJAPQgJAMgPgBQgMAAgIgKIAAAngAB5gbQgFADgEAEIAAAsQAEAFAFACQAGADAFAAQAKAAAGgIQAGgLgBgNQABgMgHgLQgFgJgLAAQgEAAgGADgAj0AsQgPABgJgNQgJgPABgRQAAgNACgSQACgKAHgLQAHgKAKgDQAQgFAPAAIABAKQgNABgOAEQgIABgFAIQgHAKgBANQALgKAMABQAOgBAJAKQAKAMgCAOQACARgLANQgKALgNAAIgCAAgAj0AiQAKABAHgJQAHgLgBgMQABgKgGgJQgIgIgJABQgEAAgHACIgLAHIAAAOQgBAOAGALQAFAKALgBgAAcAgQgKgOABgRQgBgQAKgOIADgDQAJgJANABQANAAAJAKQAJANgBAQIAAAFIg1AAQAAAMAHAKQAHAIALgBQALAAAJgGIAFAJQgFADgHADIgOACIgCAAQgOAAgKgMgABJgEQAAgLgGgIQgGgIgKABQgJgBgFAHQgHAKAAAKIArAAIAAAAgAi+AlQgHgIABgKQgBgOAMgGQASgIATABIAAgGQABgGgGgGQgGgEgIAAQgJAAgKAEIgDgJQALgFAMAAQALgBAKAHQAJAIgBALIAAA5IgKAAIAAgKQgJAMgPgBIgDAAQgJAAgHgGgAiwAFQgKADAAAKQAAAHAFAFQAGAEAGgBQAHAAAEgCQAGgCAEgGIAAgXIgDAAQgNAAgMAFgAELAqIAAg/IgpA/IgKAAIAAhQIAKAAIAAA+IApg+IALAAIAABQgAC3AqIAAhQIAKAAIAABQgAgWAqIAAhHIgWAAIAAgJIA2AAIAAAJIgVAAIAABHgAhBAqIgZglIgOAHIAAAeIgLAAIAAhQIALAAIAAAnIAHgCIAOgIQAFgFADgGQAFgJACgJIALAAQgDANgHAMQgFAJgJAEIAcAqgAD4gzIgCAAQgJAAgGgGQgGgGAAgJIAIAAQABAFAEAEQAFADAFgBQAGABAFgDQAFgEAAgFIAIAAQgBAKgGAGQgIAFgJAAgAC2g3QgCgCAAgEQAAgEACgCQAGgFAGAFQACACAAAEQAAAEgCACQgCACgEAAQgEAAgCgCg");
	this.shape.setTransform(-0.0013,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.7,-7.3,55.5,14.7);


(lib.Symbol13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgrBAQAGgGADgHQACgFAAgJIAAgJIAMAAIAAAJQAAAKgEAIQgFAIgIAGgACmAsQgKABgGgJQgMgZAMgXIAFgFQAGgFAJABQAIACAFAHQALAXgLAZQgFAIgKAAIgCAAgACigLQgDABgBAEQgGARAGATQABAGAHAAQAHAAACgGQAGgTgGgRQgBgEgEgCIgDAAIgFABgAADAmIAfgoIgHACIgJABQgJAAgIgEQgGgDgEgJQgEgHAAgLQAAgJAEgJQAFgJAGgEQAIgEAKAAQAKAAAIAEQAIAFAEAIQAEAJAAALQAAALgEAJQgGAMgJAMIgXAfgAADgOQAHAHALAAQAKAAAIgGQAEgJAAgJQAAgMgGgIQgHgIgKABQgKgBgHAHQgGAJABAKIAAAAQAAALAFAIgAhXAmIAfgoQgEACgEAAIgIABQgKAAgHgEQgIgDgEgJQgEgJAAgJQAAgJAFgJQAEgIAIgFQAIgEAKAAQAKAAAIAEQAIAGAEAHQAEAJAAALQgBALgDAJQgGALgJANIgXAfgAhXg0QgHAJABAKQgBAKAHAJQAHAHAKAAQAKAAAJgGQAEgHAAgLQAAgKgGgKQgIgIgKABIgCAAQgIAAgGAGgAiqAmIAfgoQgDACgEAAIgJABQgJAAgIgEQgHgDgEgJQgEgJAAgJQAAgJAEgJQAEgIAIgFQAJgEAJAAQAKAAAIAFQAHAEAFAIQAFAKgBAKQAAAKgEAKQgFALgJANIgYAfgAiqg0QgHAJABAKQgBAKAHAJQAHAHALAAQAKAAAIgGQAEgJAAgJQABgLgHgJQgHgIgKABIgDAAQgIAAgGAGgABfArIA5htIALAAIg6BtgABbgCQgKABgGgJQgMgZAMgZIAFgEQAGgFAIABQAIACAFAGQAMAZgMAZQgFAIgJAAIgCAAgABXg7QgDACgCADQgGATAGATQADAGAGAAQAGAAADgGQAGgTgGgTQgCgDgEgCIgDAAIgEAAg");
	this.shape.setTransform(-0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-18.8,-6.9,37.6,13.9);


(lib.Symbol12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgjBCIgDgWIg7AAIgCAWIgIAAIAAggIAGAAQAFgDAEgFQADgDABgGIACgOIAEgnIAsAAIAABGIALAAIAAAggAhLAEQgBAKgCAIQgEAIgFAEIAmAAIAAg9IgXAAgAgIAnQgHgHAAgLQAAgOAMgHQARgHASABIAAgGQABgHgGgFQgGgEgIAAQgJAAgIAEIgDgJQAKgFAMAAQALgBAJAHQAJAIgBALIAAA5IgKAAIAAgKQgIAMgQgBIgCAAQgIAAgHgGgAAEAHQgIADAAAKQgBAHAFAFQAFAEAGgBQAHAAAFgCQAGgDADgFIAAgXQgPAAgNAFgADkAiQgKgOAAgRQAAgLAFgKQADgIAJgHQAIgFAKAAIAMABIAKAFIgEAJQgJgFgJAAQgJgBgHAIQgHAIAAAMIAgAAIAAAIIggAAQAAALAHAKQAIAIAKgBQAJAAAIgFIAEAJQgEADgGACQgGABgGAAIgDAAQgOAAgJgLgAA6AkQAGgDAEgFQAEgEABgGIAFg2IAvAAIAABQIgLAAIAAhHIgaAAIgFAyQgCAHgEAFQgGAGgJAEgAjpAsIgqAAIAAhtIAlAAQAMgBALAJQAJAJgBANQAAAIgEAFQgEAGgGADQAIABAHAIQAFAGAAALQABANgJAKQgKAIgLAAIgDAAgAkIAiIAgAAQAIAAAGgGQAGgHgBgIQAAgJgFgGQgHgFgIAAIgfAAgAkIgRIAaAAQAIABAGgFQAGgHgBgHQABgIgGgHQgHgFgIAAIgZAAgAC+AsIAAgfIgRAAIgUAfIgNAAIAWggQgIgCgEgHQgEgGAAgJQAAgKAHgIQAIgHALABIAcAAIAABQgAChgXQgEAFAAAHQAAAGAEAFQAFAFAHgBIARAAIAAgfIgRAAIgBAAQgGAAgFAEgAiFAsIAAg/IgoA/IgLAAIAAhQIALAAIAAA+IAog+IALAAIAABQg");
	this.shape.setTransform(0.025,-0.0264);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-27.6,-6.6,55.3,13.2);


(lib.Symbol10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.icon();
	this.instance.parent = this;
	this.instance.setTransform(-20,-20);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-20,-20,40,40);


(lib.Symbol9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AjrBTIAAiiIAZAAIAAAOQAHgIAJgEQAKgFALAAQAJAAALAEQAKAEAIAHQAIAJAEAKQAGALgBAOQAAALgFAMQgEAJgIAKQgIAGgKAFQgVAIgUgIQgJgDgHgIIAABAgAi/g4QgGADgEAFQgFAFgCAGQgDAGAAAHQAAAHADAHQACAFAFAFQAEAEAGADQAHADAHAAQAGAAAHgDQANgFAFgMQACgGAAgIQAAgIgCgGQgCgFgFgGQgFgEgGgDQgHgDgGABIgDAAQgGAAgFACgAg1AhQgLABgJgEQgMgFgGgGQgIgIgEgLQgFgKAAgNQAAgPAFgKQAFgLAHgIQAIgHAKgEQAKgEALAAQALAAAJAFQAJADAHAIIAAgNIAZAAIAABuIgZAAIAAgOQgGAHgKAGQgJAEgKAAIgCgBgAg+g4QgGADgFAEQgFAGgCAFQgDAIAAAGQAAAHADAHQAFAMANAFQAOAGANgGQAGgDAEgEQAFgFACgFQADgHAAgHQAAgHgDgGQgCgGgFgFQgEgFgGgDQgHgCgHAAQgGAAgHACgAFHAfIAAggIgbAAIgQAgIgbAAIAUgnQgIgEgFgKQgIgRAHgSQAEgHAFgEQAFgGAJgCQAJgDAJAAIAxAAIAABugAEjg0QgEAEAAAHIABAHQAAACADADIAGAEIAJACIAVAAIAAgiIgVAAIgDAAQgHAAgFAFgADbAfIAAgrIgxAAIAAArIgaAAIAAhuIAaAAIAAArIAxAAIAAgrIAaAAIAABugABlAfIAAgrIgxAAIAAArIgaAAIAAhuIAaAAIAAArIAxAAIAAgrIAaAAIAABugAkXAfIAAhXIgvAAIAABXIgaAAIAAhuIBjAAIAABug");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-35.2,-8.3,70.5,16.6);


(lib.Symbol8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AhWBaIAAgYIhRAAIAAAYIgYAAIAAgxIANAAIAmhXIAaAAIAmBXIAMAAIAAAxgAhnAqIgZg4IgYA4IAxAAgAEKA/QgKgEgIgJQgMgMgEgRQgDgSAHgQQADgJAJgJQAIgIAKgEQAMgFAMAAQAIAAAJACQAKAEAFAEQAHAFAGAGQAFAGADAIIgXAJQgEgJgIgFQgJgGgJABQgHgBgHADQgFADgFAFQgFAEgCAGQgCAGgBAHQABAGACAHQACAGAFAEQAFAGAFABQAHADAHAAQAKAAAJgFQAHgHAEgIIAYAJQgEAIgFAHQgHAHgFAEQgHAFgIACQgIACgKABQgMgBgMgEgACIBAQgLgFgHgHQgJgJgEgJQgFgLABgNQgBgMAFgMQAEgKAJgIQAHgIALgEQAKgEAKAAQALAAAJAFQAKAEAGAHIAAgOIAaAAIAABwIgaAAIAAgPQgFAHgLAGIAAgBQgJAEgLABQgMgBgIgDgACuApQAFgDAFgEQAFgGACgFQACgIABgGQgBgGgCgGQgCgGgFgFQgFgFgFgDQgOgFgNAFQgGACgFAGQgFAFgCAFQgDAHAAAGQAAAGADAIQAFANANAFIAAAAQANAGAOgGgAA9BCIAAgkIgKACIgLAAQgLAAgJgCQgJgDgHgGQgFgFgDgIQgDgHAAgIIAAgnIAYAAIAAAiQABAKAFAFQAKAHALgCIAIAAIAJgBIAAg1IAaAAIAABwgAjjBCIAAhwIAaAAIAABwgAkOBCIAAhYIgvAAIAABYIgaAAIAAhwIBjAAIAABwgAjXg4QgGAAgGgFQgDgGAAgGQgBgHAFgFQAFgEAHAAQAHAAAFAEQAFAFgBAHQABAHgGAGQgEAEgHAAIgBAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-34.3,-9,68.69999999999999,18);


(lib.Symbol7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ACIBnIAAiiIAaAAIAAAPQAHgJAJgEQAJgEAMAAQAKAAAKADQAKAEAIAIQAHAGAFAMQAFAOAAALQAAAKgFAOQgEAJgJAJQgHAHgKAEQgVAIgUgIQgKgEgGgHIAABAgADDAfQAGgBAHgCQAMgFAGgNQACgIAAgGQAAgFgCgIQgCgFgFgGQgGgFgFgCQgGgDgHAAQgIAAgGADQgFACgFAFQgFAGgCAFQgDAFAAAIQAAAIADAFQACAFAFAHQAEAEAGADIAAAAQAGADAIAAgAijBnIAXg5IguhpIAcAAIAfBKIAehKIAbAAIhDCigAErAxQgWgIgJgWQgEgLAAgLQAAgLAEgMQAFgLAIgIQAIgHAKgFQALgFAMABQAMgBALAFQAKADAJAJQAHAHAFALQAEAMAAALIAAAJIhbAAQACAMAJAHQAKAHANAAQAKAAAJgFQAJgGADgIIAVAMQgGANgOAJQgPAJgRgBIgEAAQgKAAgKgFgAEuggQgJAGgDALIBAAAQgDgLgJgHIABAAQgKgGgLAAIgBAAQgKAAgJAHgAjvA2QgMABgMgGQgKgFgIgJQgIgMgDgLQgDgNAAgOQAAgQAEgQQAFgOAJgJQASgRAZgBIAngFIADAYIgoAEQgOABgKAIQgLAJgDAOQAFgIAKgGQAKgEAMAAQALgBAJAEQAIAEAHAHQAIAHADAJQAIAVgIAVQgJAVgVAIQgKAEgKAAIgCAAgAkEgUIgGAJQgCAHAAAEQAAAFACAHQACAFAEAFQAGAEAEACQAMAFAMgFQAKgEAFgMQACgGAAgGQAAgFgCgGQgCgGgEgDQgEgEgFgDQgHgCgGAAQgLAAgKAJgAoAAxQgMgGgIgJIASgRQAFAGAJAFQAIADAJAAQAIAAAHgDQAFgEAAgGQAAgGgFgDQgIgEgIABIgRAAIAAgVIARAAQAHAAAHgDIADgEQACgEgBgDQgBgEgDgCQgGgEgIABQgHAAgJADQgIAEgEAGIgSgQQAIgLAMgEQAWgJAXAGQAGABAHAGQAGADADAHQADAFAAAHQAAAJgEAGQgEAGgGAEQAHADAFAGQAGAGgBAKQAAAHgDAGQgEAIgFADQgGAFgJACQgIADgMAAIgCAAQgMAAgOgFgAmIAyQgLgEgHgHQgJgJgEgJQgEgLAAgNQAAgNAEgMQAFgKAIgIQAHgIALgEQAKgDAKAAQALgBAKAFQAJAEAGAHIAAgNIAaAAIAABvIgaAAIAAgOQgGAIgJADQgKAFgLAAQgMAAgIgEgAl9gjQgGACgFAFQgFAFgCAGQgDAIAAAFQAAAHADAGQAFANANAGQANAFAOgFQAGgDAEgFQAFgFACgGQADgGAAgHQAAgFgDgIQgCgFgFgGQgFgFgFgCQgHgDgHAAQgHAAgGADgAH4A0IAAhvIAaAAIAABvgAHNA0IAAgkIgVADQgLAAgKgDQgJgDgGgGQgGgFgDgGQgEgIAAgJIAAgmIAaAAIAAAiQgBAJAHAGQAKAIALgCIAIAAIAJgBIAAg2IAaAAIAABvgAAsA0IAAhvIAbAAIAABvgAgcA0IAAhXIgjAAIAAgYIBgAAIAAAYIgjAAIAABXgAIEhFQgHAAgEgGQgFgFABgGQgBgHAFgFQAFgEAHgBQAHABAFAEQAEAEAAAIQAAAHgFAFQgFAFgGAAIgBAAgAA5hFQgHAAgFgGQgEgFAAgGQAAgIAFgEQAFgEAHgBQAHABAFAEQAFAFgBAHQABAHgGAFQgFAFgGAAIgBAAg");
	this.shape.setTransform(0.025,0);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-53.3,-10.3,106.69999999999999,20.700000000000003);


(lib.Symbol6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AmwBaIAAgbIhaAAIAAAbIgXAAIAAgzIANAAIAqhyIAbAAIAqByIAOAAIAAAzgAnAAnIgdhPIgcBPIA5AAgAi1BYIAAgZIhRAAIAAAZIgXAAIAAgwIAMAAIAmhXIAaAAIAmBXIANAAIAAAwgAjFAoIgZg5IgZA5IAyAAgAHqBCQgMAAgNgFQgVgIgJgWQgFgLAAgMQAAgLAFgLQAFgLAHgIQAJgIAKgEQALgFAMAAQAMAAALAFQAKADAIAJQAHAHAGALQADAKAAAMIAAAKIhbAAQADAMAJAHQAKAHANAAQAJAAAKgFQAJgGADgJIAVANQgGANgOAJQgPAIgPAAIgCAAgAHVgVQgJAHgEAKIBAAAQgCgLgJgGIAAAAQgKgGgKAAIgCAAQgKAAgIAGgAB2A+QgKgEgIgIQgIgHgFgLQgEgLAAgNQgBgMAFgMQAEgKAJgIQAIgIAKgEQAKgEAKAAQAKAAAKAEQALAFAFAHIAAgNIAaAAIAABuIgaAAIAAgOQgGAIgKAEQgJAFgLAAQgKAAgKgEgACBgXQgGACgFAFQgDADgEAIQgDAGAAAGQAAAHADAHQAFANANAFQANAHAOgHQAFgCAFgFQAFgFACgGQACgFAAgJQAAgGgCgGQgCgFgFgGQgFgFgFgCQgHgEgHAAQgHAAgGAEgAh5A+QgKgEgIgIQgJgIgEgKQgFgNAAgLQAAgMAFgMQAEgLAJgHQAHgIAKgEQALgEAKAAQAKAAAKAEQAKAFAGAHIAAgNIAaAAIAABuIgaAAIAAgOQgGAJgKADIAAAAQgKAFgLAAQgJAAgKgEgAhvgYQgGAEgEAEQgFAEgDAHQgDAGABAGQgBAHADAHQAFANANAFQAOAGANgGQAHgCADgFQAFgFACgGQADgGAAgIQAAgGgDgGQgBgFgGgGQgEgFgGgDQgGgCgHAAQgHAAgHACgAlxA9QgKgEgJgIQgHgIgFgLQgJgWAJgWQAEgJAIgKQAJgIAKgEQAMgFALAAQAMAAAKAFQALAEAIAIQANANADARQADARgGAQQgKAWgWAJQgKAFgMAAQgLAAgMgFgAlygPQgDADgDAHQgDAHAAAGQAAAGADAHQADAHADAEQAGAFAFACQAGADAHAAQAHAAAFgDQANgGAFgMQADgHAAgGQAAgGgDgHQgFgMgNgGQgEgCgIAAQgPAAgJAKgAAeBAIg0AAIAAhvIAzAAQAQgBANAIQAMAJgBAOQABAQgOAGQAHADAFAHQAFAIAAAIQABAPgNAJQgNAJgPAAIgDAAgAADAqIAbAAQAHAAAFgDIABgCQADgDAAgFQAAgFgEgEQgGgDgGAAIgbAAgAADgEIAbAAQAFABAFgDQAFgEgCgFQABgFgEgDQgFgEgFABIgbAAgAFvBAIAAhYIgkAAIAAgXIBhAAIAAAXIgjAAIAABYgAEmA/IAAhJIgyBJIgaAAIAAhuIAaAAIAABHIAxhHIAbAAIAABugAEAg6QgGgDgEgEQgEgEgDgHQgBgGAAgHIARAAQAAAHAEAGQAGAFAGAAQAHAAAFgFQAEgHgBgGIASAAQAAAHgCAGQgCAHgEAEQgFAFgGACQgHACgHAAQgHAAgIgCg");
	this.shape.setTransform(0,-0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-54.6,-9,109.30000000000001,18);


(lib.Symbol4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.bf(img._336x280_pic, null, new cjs.Matrix2D(2.027,0,0,1,-15.2,-140)).s().p("AiXV4MAAAgrvIEwAAMAAAArvg");
	this.shape.setTransform(-168.2,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.bf(img._336x280_pic, null, new cjs.Matrix2D(1,0,0,1,-175.5,-140)).s().p("A5EV4MAAAgrvMAyJAAAMAAAArvg");
	this.shape_1.setTransform(7.525,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-183.4,-140,351.4,280);


(lib.Symbol3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.machine();
	this.instance.parent = this;
	this.instance.setTransform(-152,-86);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-152,-86,304,172);


(lib.Symbol2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.bg();
	this.instance.parent = this;
	this.instance.setTransform(-168,-30.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-168,-30.5,336,61);


(lib.Symbol1copy = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Am3AfIAAgKIAiAAIAAAMQAAAMAMAAQAKAAACgJQACgEgCgFQgCgHgbgOQgYgNgDgOQgCgJABgIQAFgcAnAAQArAAAAAfIAAAJIggAAIAAgIQAAgFgDgDQgDgDgFAAQgLAAgBAIQgBADABAEQACAGAaAOQAaANADAPQABAJgBAMQgEAcgoAAQguAAAAgkgAgeAfIAAgKIAhAAIAAAMQAAALAMAAQALAAABgIQACgEgCgFQgCgHgZgOQgZgNgDgOQgCgIACgJQAFgcAlAAQAqAAAAAgIAAAIIgfAAIAAgHQAAgMgLAAQgKAAgCAJIAAAGQACAGAaAOQAZANADAPQADAHgCANQgEAdgoAAQgtAAAAgkgABZAjIAAhhIAfAAIAABcIABAEQABAKALAAQAKAAACgKIAAgEIAAhcIAgAAIAABhQgDAfgpAAQgpAAgDgfgAFfAiIAAgIIAAg9QAEgfAoAAQApAAAEAfIAAANIggAAIAAgMQgCgJgLAAQgLAAgBAJIgBAGIAAA9QACAJALAAQAMAAABgJIAAgXIgMAAIAAgRIAsAAIAAApQgEAfgpAAQgpAAgDgfgAhcA+IgBhzIgVBzIggAAIgWhzIgBBzIgfAAIACh8IA0AAIAQBhIAQhhIAzAAIADB8gAkDA+IgRhzIgSBzIgiAAIAXh8IA4AAIAYB8gAERA9IgghnIACBnIgfAAIAAh7IAvAAIAdBkIgBhkIAfAAIAAB7g");
	this.shape.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44,-6.7,88.1,13.5);


(lib.Symbol1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("Am3AfIAAgKIAiAAIAAAMQAAAMAMAAQAKAAACgJQACgEgCgFQgCgHgbgOQgYgNgDgOQgCgJABgIQAFgcAnAAQArAAAAAfIAAAJIggAAIAAgIQAAgFgDgDQgDgDgFAAQgLAAgBAIQgBADABAEQACAGAaAOQAaANADAPQABAJgBAMQgEAcgoAAQguAAAAgkgAgeAfIAAgKIAhAAIAAAMQAAALAMAAQALAAABgIQACgEgCgFQgCgHgZgOQgZgNgDgOQgCgIACgJQAFgcAlAAQAqAAAAAgIAAAIIgfAAIAAgHQAAgMgLAAQgKAAgCAJIAAAGQACAGAaAOQAZANADAPQADAHgCANQgEAdgoAAQgtAAAAgkgABZAjIAAhhIAfAAIAABcIABAEQABAKALAAQAKAAACgKIAAgEIAAhcIAgAAIAABhQgDAfgpAAQgpAAgDgfgAFfAiIAAgIIAAg9QAEgfAoAAQApAAAEAfIAAANIggAAIAAgMQgCgJgLAAQgLAAgBAJIgBAGIAAA9QACAJALAAQAMAAABgJIAAgXIgMAAIAAgRIAsAAIAAApQgEAfgpAAQgpAAgDgfgAhcA+IgBhzIgVBzIggAAIgWhzIgBBzIgfAAIACh8IA0AAIAQBhIAQhhIAzAAIADB8gAkDA+IgRhzIgSBzIgiAAIAXh8IA4AAIAYB8gAERA9IgghnIACBnIgfAAIAAh7IAvAAIAdBkIgBhkIAfAAIAAB7g");
	this.shape.setTransform(0.025,0.025);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-44,-6.7,88.1,13.5);


(lib.Symbol9_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Детальніше
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgWA2QgLgFgIgIQgHgIgFgKQgDgLAAgMQgBgLAFgLQAEgKAIgIQAIgIAKgFQALgEALAAQAMAAALAEQAKAFAIAHQAIAIAEAKQAFALgBAMIAAAJIhZAAQACAMAKAHQAIAHANAAQALAAAIgFQAIgGAEgIIAVAMQgHAOgNAHQgNAJgTAAQgMAAgLgEgAAfgLQgDgMgIgFQgIgHgMAAQgKABgJAGQgIAGgEALIA+AAIAAAAg");
	this.shape_1.setTransform(141.7,26.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AhKA3IAAhtIAZAAIAABWIAmAAIAAhWIAYAAIAABWIAkAAIAAhWIAaAAIAABtg");
	this.shape_2.setTransform(127.3,26.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgMBNIAAhuIAZAAIAABugAgLgwQgEgFAAgHQAAgHAEgFQAFgEAGAAQAIAAAEAEQAEAFAAAHQAAAHgEAFQgEAEgIAAQgHAAgEgEg");
	this.shape_3.setTransform(117.025,24.325);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAYA3IAAgsIgvAAIAAAsIgaAAIAAhtIAaAAIAAArIAvAAIAAgrIAaAAIAABtg");
	this.shape_4.setTransform(109.325,26.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgtA3IAAhtIAZAAIAAAgIAWAAQAKABAIADQAIADAGAFQAGAGADAFQADAIAAAIQAAAHgDAHQgDAIgGAFQgGAFgIAEQgIACgKAAgAgUAhIAVAAQAJAAAFgFQAGgFAAgGQAAgIgGgFQgFgEgJAAIgVAAg");
	this.shape_5.setTransform(98.725,26.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAeA3IgehLIgeBLIgaAAIAthtIAXAAIAtBtg");
	this.shape_6.setTransform(87.5,26.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgXA2QgJgEgIgHQgIgIgEgKQgFgLAAgOQAAgNAFgLQAEgLAIgHQAIgHAJgEQAKgEALAAQAKAAAJAEQAJAFAHAGIAAgMIAZAAIAABtIgZAAIAAgOQgHAIgJAFQgKAEgJAAQgKAAgLgEgAgLgfQgHADgEAEQgFAFgCAGQgDAGAAAHQAAAHADAGQACAGAFAFQAEAFAHACQAFAEAHAAQAHAAAGgEQAGgCAFgFQAEgFACgGQADgGAAgHQAAgHgDgGQgCgGgEgFQgFgEgGgDQgGgCgHgBQgHABgFACg");
	this.shape_7.setTransform(75.1,26.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgMA3IAAhWIgjAAIAAgXIBfAAIAAAXIgjAAIAABWg");
	this.shape_8.setTransform(63.875,26.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgWA2QgLgFgIgIQgHgIgEgKQgFgLAAgMQABgLAEgLQAEgKAIgIQAIgIAKgFQALgEALAAQAMAAALAEQAKAFAIAHQAIAIAEAKQAEALABAMIAAAJIhaAAQADAMAIAHQAKAHAMAAQALAAAIgFQAIgGAEgIIAVAMQgIAOgMAHQgNAJgTAAQgMAAgLgEgAAfgLQgDgMgIgFQgIgHgMAAQgKABgJAGQgJAGgDALIA+AAIAAAAg");
	this.shape_9.setTransform(52.75,26.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAsBSIAAgaIhYAAIAAAaIgYAAIAAgyIAOAAIAphxIAaAAIAqBxIAOAAIAAAygAAcAgIgchPIgbBPIA3AAg");
	this.shape_10.setTransform(39.575,26.425);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]}).wait(1));

	// Layer_1
	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f().s("#FFFFFF").ss(3,1,1).p("AopjaIRTAAQBbAABABAQBABAAABaQAABbhABAQhABAhbAAIxTAAQhaAAhBhAQhAhAAAhbQAAhaBAhAQBBhABaAAg");
	this.shape_11.setTransform(90.05,25.55);

	this.timeline.addTween(cjs.Tween.get(this.shape_11).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol9_1, new cjs.Rectangle(11.3,2.2,157.6,46.8), null);


(lib.Symbol8_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AqTAuIAAgOIAzAAIAAASQAAARASAAQAPAAADgNQADgGgDgIQgDgKgogVQgkgUgFgVQgDgNACgNQAHgqA7AAQBAAAAAAvIAAAOIgvAAIAAgMQgBgIgEgEQgFgFgIAAQgPAAgCAMQgCAEACAHQADAIAnAWQAnAUAEAWQACANgCASQgGArg8AAQhFAAAAg3gAgtAuIAAgPIAxAAIAAATQAAAQATAAQARAAABgMQADgGgDgIQgEgKgmgVQglgUgEgVQgDgMACgNQAIgqA4AAQBAAAgBAvIAAANIguAAIAAgLQAAgSgSAAQgOAAgDANIAAAKQACAIAoAWQAmAUAFAWQADAKgDAUQgGArg8AAQhDAAAAg2gACFA1IAAiTIAwAAIAACLIAAAGQADAPAPAAQAQAAACgPIABgGIAAiLIAwAAIgBCTQgDAug/AAQg8AAgGgugAIOAzIAAhoQAHguA8AAQA9AAAFAuIAAATIgvAAIAAgSQgDgNgQAAQgRAAgCANIgBAJIAABdQACANASAAQARAAACgNIAAgjIgSAAIAAgaIBCAAIgBA+QgFAug9AAQg+AAgFgugAiKBdIgCitIggCtIgwAAIggitIgBCtIgwAAIAEi7IBNAAIAYCSIAYiSIBMAAIAFC7gAmFBdIgZitIgbCtIgzAAIAji7IBTAAIAkC7gAGZBcIgvicIACCcIgvAAIAAi6IBHAAIAtCXIgDiXIAvAAIAAC6g");
	this.shape_1.setTransform(66,10.075);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = getMCSymbolPrototype(lib.Symbol8_1, new cjs.Rectangle(0,0,132,20.2), null);


(lib.Symbol1copy_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AwrCNIAAjvIAlAAIAAAVQAJgMAPgHQAOgGAQAAQAPAAAPAFQAQAGAKALQAMAMAGAQQAHAPAAAUQAAAUgHAQQgHAQgMALQgLAKgPAHQgOAGgPAAQgQAAgOgHQgPgGgJgLIAABggAvphAQgKAEgGAIQgGAGgFAJQgDAKAAAKQAAALADAIQAFAJAGAHQAGAHAKAEQAJAEAKAAQALAAAJgEQAJgEAGgGQAHgIADgJQAFgIAAgLQAAgLgFgJQgDgJgHgHQgGgHgJgEQgJgDgLAAQgKAAgJADgARlA/QgOgHgMgKQgMgLgHgQQgHgQAAgUQAAgUAHgPQAHgQAMgMQALgLAPgGQAOgFAQAAQAQAAAOAFQAOAHAJAKIAAgSIAmAAIAACjIgmAAIAAgWQgJAMgOAHQgOAHgRAAQgPAAgOgGgAR0hAQgIAEgHAHQgHAHgEAJQgEAJABALQgBALAEAIQAEAJAHAIQAHAGAIAEQAKAEALAAQAKAAAJgEQAKgEAGgHQAGgHAFgJQACgIAAgLQAAgKgCgKQgFgJgGgGQgGgIgKgEQgJgDgKAAQgLAAgKADgAFRA/QgOgHgMgKQgLgLgIgQQgHgQAAgUQAAgUAHgPQAIgQALgMQAMgLAOgGQAOgFAQAAQARAAAOAFQANAHAJAKIAAgSIAnAAIAACjIgnAAIAAgWQgJAMgNAHQgOAHgSAAQgPAAgOgGgAFihAQgKAEgHAHQgGAHgEAJQgEAJAAALQAAALAEAIQAEAJAGAIQAHAGAKAEQAJAEAKAAQALAAAIgEQAKgEAHgHQAFgHAFgJQADgIAAgLQAAgKgDgKQgFgJgFgGQgHgIgKgEQgIgDgLAAQgKAAgJADgAiCA/QgOgHgNgKQgLgLgHgQQgHgQAAgUQAAgUAHgPQAHgQALgMQAMgLAPgGQAOgFAQAAQAQAAAOAFQAOAHAIAKIAAgSIAnAAIAACjIgnAAIAAgWQgIAMgOAHQgOAHgRAAQgPAAgOgGgAhyhAQgJAEgHAHQgHAHgDAJQgEAJAAALQAAALAEAIQADAJAHAIQAHAGAJAEQAJAEAKAAQALAAAJgEQAJgEAHgHQAGgHAEgJQADgIAAgLQAAgKgDgKQgEgJgGgGQgHgIgJgEQgJgDgLAAQgKAAgJADgAs+A/QgOgHgMgKQgLgLgIgQQgGgQAAgUQAAgUAGgPQAIgQALgMQALgLAPgGQAPgFAQAAQAQAAANAFQAPAHAJAKIAAgSIAmAAIAACjIgmAAIAAgWQgJAMgPAHQgOAHgQAAQgPAAgPgGgAsuhAQgJAEgHAHQgGAHgEAJQgDAJAAALQAAALADAIQAEAJAGAIQAHAGAJAEQAKAEAKAAQAKAAAKgEQAJgEAHgHQAFgHAFgJQADgIAAgLQAAgKgDgKQgFgJgFgGQgHgIgJgEQgKgDgKAAQgKAAgKADgAP3BBIAAhBIhIAAIAABBIglAAIAAijIAlAAIAAA/IBIAAIAAg/IAnAAIAACjgANLBBIAAhsIhKBsIglAAIAAijIAlAAIAABpIBIhpIAoAAIAACjgAHjBBIAAijIAnAAIAACAIA2AAIAAiAIAmAAIAACAIA2AAIAAiAIAmAAIAACjgADkBBIAAhrIg0A6Ig0g5IAABqIglAAIAAijIAkAAIA1BAIA4hAIAiAAIAACjgAjwBBIAAhBIhHAAIAABBIgmAAIAAijIAmAAIAAA/IBHAAIAAg/IAmAAIAACjgAn5BBIAAijIAmAAIAAAwIAiAAQAOAAANAFQAMAFAJAHQAIAIAFAKQAFALAAALQAAAMgFAKQgFAKgIAJQgJAHgMAFQgMAFgPAAgAnTAgIAgAAQANAAAJgIQAIgGAAgLQAAgKgIgHQgJgHgNAAIggAAgAoyBBIgthyIgtByIgnAAIBCijIAkAAIBCCjgAxrBBIAAioIhNAAIAACoIglAAIAAjNICYAAIAADNg");
	this.shape_1.setTransform(0.1,-4.775);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124.5,-18.8,249.2,28.1);


(lib.Symbol1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AwrCNIAAjvIAlAAIAAAVQAJgMAPgHQAOgGAQAAQAPAAAPAFQAQAGAKALQAMAMAGAQQAHAPAAAUQAAAUgHAQQgHAQgMALQgLAKgPAHQgOAGgPAAQgQAAgOgHQgPgGgJgLIAABggAvphAQgKAEgGAIQgGAGgFAJQgDAKAAAKQAAALADAIQAFAJAGAHQAGAHAKAEQAJAEAKAAQALAAAJgEQAJgEAGgGQAHgIADgJQAFgIAAgLQAAgLgFgJQgDgJgHgHQgGgHgJgEQgJgDgLAAQgKAAgJADgARlA/QgOgHgMgKQgMgLgHgQQgHgQAAgUQAAgUAHgPQAHgQAMgMQALgLAPgGQAOgFAQAAQAQAAAOAFQAOAHAJAKIAAgSIAmAAIAACjIgmAAIAAgWQgJAMgOAHQgOAHgRAAQgPAAgOgGgAR0hAQgIAEgHAHQgHAHgEAJQgEAJABALQgBALAEAIQAEAJAHAIQAHAGAIAEQAKAEALAAQAKAAAJgEQAKgEAGgHQAGgHAFgJQACgIAAgLQAAgKgCgKQgFgJgGgGQgGgIgKgEQgJgDgKAAQgLAAgKADgAFRA/QgOgHgMgKQgLgLgIgQQgHgQAAgUQAAgUAHgPQAIgQALgMQAMgLAOgGQAOgFAQAAQARAAAOAFQANAHAJAKIAAgSIAnAAIAACjIgnAAIAAgWQgJAMgNAHQgOAHgSAAQgPAAgOgGgAFihAQgKAEgHAHQgGAHgEAJQgEAJAAALQAAALAEAIQAEAJAGAIQAHAGAKAEQAJAEAKAAQALAAAIgEQAKgEAHgHQAFgHAFgJQADgIAAgLQAAgKgDgKQgFgJgFgGQgHgIgKgEQgIgDgLAAQgKAAgJADgAiCA/QgOgHgNgKQgLgLgHgQQgHgQAAgUQAAgUAHgPQAHgQALgMQAMgLAPgGQAOgFAQAAQAQAAAOAFQAOAHAIAKIAAgSIAnAAIAACjIgnAAIAAgWQgIAMgOAHQgOAHgRAAQgPAAgOgGgAhyhAQgJAEgHAHQgHAHgDAJQgEAJAAALQAAALAEAIQADAJAHAIQAHAGAJAEQAJAEAKAAQALAAAJgEQAJgEAHgHQAGgHAEgJQADgIAAgLQAAgKgDgKQgEgJgGgGQgHgIgJgEQgJgDgLAAQgKAAgJADgAs+A/QgOgHgMgKQgLgLgIgQQgGgQAAgUQAAgUAGgPQAIgQALgMQALgLAPgGQAPgFAQAAQAQAAANAFQAPAHAJAKIAAgSIAmAAIAACjIgmAAIAAgWQgJAMgPAHQgOAHgQAAQgPAAgPgGgAsuhAQgJAEgHAHQgGAHgEAJQgDAJAAALQAAALADAIQAEAJAGAIQAHAGAJAEQAKAEAKAAQAKAAAKgEQAJgEAHgHQAFgHAFgJQADgIAAgLQAAgKgDgKQgFgJgFgGQgHgIgJgEQgKgDgKAAQgKAAgKADgAP3BBIAAhBIhIAAIAABBIglAAIAAijIAlAAIAAA/IBIAAIAAg/IAnAAIAACjgANLBBIAAhsIhKBsIglAAIAAijIAlAAIAABpIBIhpIAoAAIAACjgAHjBBIAAijIAnAAIAACAIA2AAIAAiAIAmAAIAACAIA2AAIAAiAIAmAAIAACjgADkBBIAAhrIg0A6Ig0g5IAABqIglAAIAAijIAkAAIA1BAIA4hAIAiAAIAACjgAjwBBIAAhBIhHAAIAABBIgmAAIAAijIAmAAIAAA/IBHAAIAAg/IAmAAIAACjgAn5BBIAAijIAmAAIAAAwIAiAAQAOAAANAFQAMAFAJAHQAIAIAFAKQAFALAAALQAAAMgFAKQgFAKgIAJQgJAHgMAFQgMAFgPAAgAnTAgIAgAAQANAAAJgIQAIgGAAgLQAAgKgIgHQgJgHgNAAIggAAgAoyBBIgthyIgtByIgnAAIBCijIAkAAIBCCjgAxrBBIAAioIhNAAIAACoIglAAIAAjNICYAAIAADNg");
	this.shape_1.setTransform(0.1,-4.775);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-124.5,-18.8,249.2,28.1);


(lib.Symbol25 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.instance = new lib.Symbol9_1();
	this.instance.parent = this;
	this.instance.setTransform(-0.05,30.55,1,1,0,0,0,90,25.5);

	this.instance_1 = new lib.Symbol8_1();
	this.instance_1.parent = this;
	this.instance_1.setTransform(-0.05,-42.4,1,1,0,0,0,66,10.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78.8,-52.5,157.6,106.5);


(lib.Symbol20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Symbol_24
	this.instance = new lib.Symbol24("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(-4.65,116.15);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:36.15,alpha:1},13,cjs.Ease.get(1)).wait(1));

	// Symbol_23
	this.instance_1 = new lib.Symbol23("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(-37.4,68.95);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:8.95,alpha:1},13,cjs.Ease.get(1)).wait(1));

	// Symbol_22
	this.instance_2 = new lib.Symbol22("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(0.15,28.65);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-11.35,alpha:1},13,cjs.Ease.get(1)).wait(1));

	// Symbol_21
	this.instance_3 = new lib.Symbol21("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(-24.05,-16.5);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:-36.5,alpha:1},13,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-59,-44.3,118.1,168.7);


(lib.Symbol15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_2
	this.instance = new lib.Symbol17("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(139.05,9.3);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-0.1},11,cjs.Ease.get(1)).wait(1));

	// Layer_1
	this.instance_1 = new lib.Symbol16("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(78.6,-9.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:0.15},11,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-30.3,-15,199.60000000000002,30.1);


(lib.Symbol11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Symbol_14
	this.instance = new lib.Symbol14("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(172.9,19.05);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-0.25},12,cjs.Ease.get(1)).wait(1));

	// Symbol_13
	this.instance_1 = new lib.Symbol13("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(126.35,0.35);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({x:-0.1},12,cjs.Ease.get(1)).wait(1));

	// Symbol_12
	this.instance_2 = new lib.Symbol12("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(77.3,-19.75);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({x:0.35},12,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-28,-26.4,228.7,52.8);


(lib.Symbol5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Symbol_9
	this.instance = new lib.Symbol9("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(18.9,76.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:36.4,alpha:1},13,cjs.Ease.get(1)).wait(1));

	// Symbol_8
	this.instance_1 = new lib.Symbol8("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(20.4,40.05);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({y:10.05,alpha:1},13,cjs.Ease.get(1)).wait(1));

	// Symbol_7
	this.instance_2 = new lib.Symbol7("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(1.2,8.45);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({y:-11.55,alpha:1},13,cjs.Ease.get(1)).wait(1));

	// Symbol_6
	this.instance_3 = new lib.Symbol6("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(-0.1,-25.65);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).to({y:-35.65,alpha:1},13,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-54.7,-44.6,109.5,129.3);


// stage content:
(lib._300x250 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{loop:1});

	// timeline functions:
	this.frame_0 = function() {
		t = 0;
	}
	this.frame_365 = function() {
		if (t>0) { this.stop();}
	}
	this.frame_416 = function() {
		t++;
		this.gotoAndPlay('loop');
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(365).call(this.frame_365).wait(51).call(this.frame_416).wait(1));

	// Layer_22
	this.instance = new lib.Symbol25("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(150.05,119.4,0.8929,0.8929,0,0,0,0.1,0.8);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(355).to({_off:false},0).to({alpha:1},10).wait(52));

	// Layer_19
	this.instance_1 = new lib.Symbol20("synched",0,false);
	this.instance_1.parent = this;
	this.instance_1.setTransform(211.15,163.3,0.8929,0.8929);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(281).to({_off:false},0).wait(67).to({startPosition:13},0).to({alpha:0},10).wait(59));

	// Layer_18
	this.instance_2 = new lib.Tween20copy("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(149.85,142.8,0.6388,0.6388);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(272).to({_off:false},0).to({regY:0.1,y:71.4,alpha:1},15,cjs.Ease.get(1)).wait(61).to({startPosition:0},0).to({alpha:0},10).wait(59));

	// Layer_21
	this.instance_3 = new lib.Symbol1copy_1("synched",0);
	this.instance_3.parent = this;
	this.instance_3.setTransform(150.15,89.85,0.6388,0.6388,0,0,0,0.1,0.1);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(272).to({_off:false},0).to({y:54.15,alpha:1},15,cjs.Ease.get(1)).wait(61).to({startPosition:0},0).to({alpha:0},10).wait(59));

	// Layer_14
	this.instance_4 = new lib.Symbol19("synched",0);
	this.instance_4.parent = this;
	this.instance_4.setTransform(85.25,320.45,0.8929,0.8929);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(272).to({_off:false},0).to({y:166.05},15,cjs.Ease.get(1)).wait(61).to({startPosition:0},0).to({alpha:0},10).wait(59));

	// Layer_16 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_269 = new cjs.Graphics().p("EgXbAnKMAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_270 = new cjs.Graphics().p("EgXbAkoMAAAgnCMAu3AAAMAAAAnCg");
	var mask_graphics_271 = new cjs.Graphics().p("EgXbAiSMAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_272 = new cjs.Graphics().p("EgXbAgGMAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_273 = new cjs.Graphics().p("A3beFMAAAgnCMAu3AAAMAAAAnCg");
	var mask_graphics_274 = new cjs.Graphics().p("A3bcQMAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_275 = new cjs.Graphics().p("A3bamMAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_276 = new cjs.Graphics().p("A3bZHMAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_277 = new cjs.Graphics().p("A3bXzMAAAgnCMAu3AAAMAAAAnCg");
	var mask_graphics_278 = new cjs.Graphics().p("A3bWrMAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_279 = new cjs.Graphics().p("A3bVtMAAAgnCMAu3AAAMAAAAnCg");
	var mask_graphics_280 = new cjs.Graphics().p("A3bU7MAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_281 = new cjs.Graphics().p("A3bUUMAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_282 = new cjs.Graphics().p("A3bT4MAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_283 = new cjs.Graphics().p("A3bTnMAAAgnDMAu3AAAMAAAAnDg");
	var mask_graphics_284 = new cjs.Graphics().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(269).to({graphics:mask_graphics_269,x:149.95,y:250.6497}).wait(1).to({graphics:mask_graphics_270,x:149.95,y:234.4486}).wait(1).to({graphics:mask_graphics_271,x:149.95,y:219.3736}).wait(1).to({graphics:mask_graphics_272,x:149.95,y:205.3986}).wait(1).to({graphics:mask_graphics_273,x:149.95,y:192.5486}).wait(1).to({graphics:mask_graphics_274,x:149.95,y:180.8236}).wait(1).to({graphics:mask_graphics_275,x:149.95,y:170.2236}).wait(1).to({graphics:mask_graphics_276,x:149.95,y:160.7236}).wait(1).to({graphics:mask_graphics_277,x:149.95,y:152.3486}).wait(1).to({graphics:mask_graphics_278,x:149.95,y:145.0736}).wait(1).to({graphics:mask_graphics_279,x:149.95,y:138.9486}).wait(1).to({graphics:mask_graphics_280,x:149.95,y:133.8986}).wait(1).to({graphics:mask_graphics_281,x:149.95,y:129.9986}).wait(1).to({graphics:mask_graphics_282,x:149.95,y:127.1986}).wait(1).to({graphics:mask_graphics_283,x:149.95,y:125.5236}).wait(1).to({graphics:mask_graphics_284,x:149.95,y:124.95}).wait(1).to({graphics:null,x:0,y:0}).wait(132));

	// Layer_15
	this.instance_5 = new lib.Symbol1copy("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(249.25,17.7,0.8673,0.8673,0,0,0,0.1,0.1);
	this.instance_5._off = true;

	var maskedShapeInstanceList = [this.instance_5];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(269).to({_off:false},0).wait(79).to({startPosition:0},0).to({alpha:0},10).wait(59));

	// Layer_13
	this.instance_6 = new lib.Symbol18("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(149.95,376.3,0.8929,0.8929);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(269).to({_off:false},0).to({y:124.95},15,cjs.Ease.get(1)).wait(133));

	// Layer_1
	this.instance_7 = new lib.Symbol1("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(249.25,17.7,0.8673,0.8673,0,0,0,0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(417));

	// Layer_12
	this.instance_8 = new lib.Symbol15("synched",0,false);
	this.instance_8.parent = this;
	this.instance_8.setTransform(257.8,163.65,0.8929,0.8929);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(215).to({_off:false},0).wait(202));

	// Layer_4
	this.instance_9 = new lib.Symbol11("synched",0,false);
	this.instance_9.parent = this;
	this.instance_9.setTransform(258.35,171.95,0.8929,0.8929);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(157).to({_off:false},0).wait(50).to({startPosition:12},0).to({alpha:0},11).to({_off:true},1).wait(198));

	// Layer_3
	this.instance_10 = new lib.Symbol10("synched",0);
	this.instance_10.parent = this;
	this.instance_10.setTransform(258.5,120.05,1.4732,1.4732,0,0,0,0.1,0.1);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(151).to({_off:false},0).to({regX:0,regY:0,scaleX:0.8929,scaleY:0.8929,x:258.35,y:119.9,alpha:1},13).wait(253));

	// Layer_9
	this.instance_11 = new lib.Symbol5("synched",0,false);
	this.instance_11.parent = this;
	this.instance_11.setTransform(237.45,146.2,0.8929,0.8929);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(83).to({_off:false},0).wait(60).to({startPosition:13},0).to({alpha:0},12).to({_off:true},1).wait(261));

	// Layer_8
	this.instance_12 = new lib.Tween20("synched",0);
	this.instance_12.parent = this;
	this.instance_12.setTransform(150.45,102.1,0.6388,0.6388,0,0,0,0.1,0.1);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(9).to({_off:false},0).to({y:66.4,alpha:1},14,cjs.Ease.get(1)).wait(46).to({startPosition:0},0).to({regX:0.4,regY:0.2,scaleX:0.5678,scaleY:0.5678,x:216.5,y:76.95},19,cjs.Ease.quadInOut).wait(329));

	// Layer_7
	this.instance_13 = new lib.Symbol1_1("synched",0);
	this.instance_13.parent = this;
	this.instance_13.setTransform(150.75,67,0.6389,0.6389,0,0,0,0.1,0.1);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(9).to({_off:false},0).to({y:49.15,alpha:1},14,cjs.Ease.get(1)).wait(46).to({scaleX:0.6388,scaleY:0.6388},0).to({regY:0.2,scaleX:0.5797,scaleY:0.5797,x:216.7,y:59.8},19,cjs.Ease.quadInOut).wait(329));

	// Layer_10
	this.instance_14 = new lib.Symbol4("synched",0);
	this.instance_14.parent = this;
	this.instance_14.setTransform(198.65,110.25,1.0971,1.0971);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(73).to({_off:false},0).to({scaleX:0.8929,scaleY:0.8929,x:149.95,y:124.95,alpha:1},19,cjs.Ease.quadInOut).wait(325));

	// Layer_6
	this.instance_15 = new lib.Symbol3("synched",0);
	this.instance_15.parent = this;
	this.instance_15.setTransform(-120.45,173.2,0.8929,0.8929);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).to({x:149.95},16,cjs.Ease.get(1)).wait(57).to({startPosition:0},0).to({regX:0.2,regY:0.2,scaleX:0.7422,scaleY:0.7422,x:111.05,y:176.45},19,cjs.Ease.quadInOut).wait(325));

	// Layer_2
	this.instance_16 = new lib.Symbol2("synched",0);
	this.instance_16.parent = this;
	this.instance_16.setTransform(150.85,222.75,0.8929,0.8929);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).to({alpha:1},16).wait(401));

	// Layer_5
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A6PV4MAAAgrvMA0fAAAMAAAArvg");
	this.shape.setTransform(149.9993,124.9994,0.8929,0.8929);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(417));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-106.1,81.7,543.6,419.6);
// library properties:
lib.properties = {
	id: '8A19DA29023744B395B67E6355C065DB',
	width: 300,
	height: 250,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"_336x280_pic.jpg", id:"_336x280_pic"},
		{src:"bg.jpg", id:"bg"},
		{src:"icon.png", id:"icon"},
		{src:"machine.png", id:"machine"},
		{src:"machine_icon.png", id:"machine_icon"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['8A19DA29023744B395B67E6355C065DB'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}			
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;			
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});			
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;			
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;